### ISSUE TITLE
High Elf features Suggestion

### ISSUE THREAD

**Issue by nsYW** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2#1003]
**Describe your suggestion in full detail below:**
I think the features of the High Elf model are too easy to old. I hope your team can make the High Elf as young as the Night elf.

![QQ截图20230111193703](https://user-images.githubusercontent.com/24467602/211796868-d24433a4-4ccb-495e-ae6b-0cac7e84018d.png)
![QQ截图20230111193651](https://user-images.githubusercontent.com/24467602/211796888-18252a3a-4b85-4706-ae5f-511a9556f875.png)

**Comment by zumbak04** [comment]
Skip one day. It's a refresh problem.
