### ISSUE TITLE
Localization defect

### ISSUE THREAD

**Issue by nsYW** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2#1005]
**Mod version:**
Pre-Alpha (main branch)

**Are you using any submods/mods? If so, which?**
No

**Please explain your issue in as much detail as possible:**
localization/simp_chinese/names/wc_character_names_l_simp_chinese.yml
At 18247 line, the key value has a redundant ' " ' .
As shown below :

**Upload screenshots of the problem localization:**
![图片](https://user-images.githubusercontent.com/24467602/212478255-139a3b6a-3a00-478b-af71-1d66cc8bce07.png)

**Comment by VespertinePetrichor** [comment]
Thanks, it'll be fixed in #936
