### ISSUE TITLE
Brave Trait for Arthas

### ISSUE THREAD

**Issue by PearlForger** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2#1009]
**Describe your suggestion in full detail below:**

Developers, I thank you for all your fantastic work on this project, and especially to make this Ck3 adaptation of Azeroth as lore accurate as possible. 

With lore accuracy in mind, I'd like to point your attention to  Arthas Menethil's IG character, and his current three traits.
I believe if **one** trait is added, the brave trait, it would further balance ck3 gameplay for Arthas and add to lore accuracy.

I will now crosspost my reasons for adding the brave trait to Arthas's character, from DS:

![image](https://user-images.githubusercontent.com/124048741/215761057-c4344257-dfd4-4f9c-9167-55788ff230fe.jpeg)
![image](https://user-images.githubusercontent.com/124048741/215761104-12122b77-1c26-4761-9142-ec7953b27bdc.jpeg)

Thanks for your consideration.

**Comment by Grekopithikos** [comment]
Speaking of which I think it would be most fitting for Garithos to be arrogant
