### ISSUE TITLE
List of vanilla localisation to fix

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2#101]
**Mod version:**
0121c81f

**Are you using any submods/mods? If so, which?**
`-`

**Please explain your issue in as much detail as possible:**
List of lines that have rl references and/or not suitable and needs to be changed

**Upload screenshots of the problem localization:**

- [x] setting_default_regional_heresy_desc <details> <summary>Click to expand</summary> 
![image](https://user-images.githubusercontent.com/46576860/105395894-5047cb00-5c30-11eb-9e11-009c265806a1.png)
 </details>

- [x] game_concept_religious_family_desc <details> <summary>Click to expand</summary> 
![image](https://user-images.githubusercontent.com/46576860/105396376-dfed7980-5c30-11eb-89f9-e1ac5369e916.png)
 </details>

- [x] game_concept_religion_desc <details> <summary>Click to expand</summary> 
![image](https://user-images.githubusercontent.com/46576860/105396699-3f4b8980-5c31-11eb-8df5-9226a6a313d0.png)
 </details>

- [x] game_concept_organized_desc <details> <summary>Click to expand</summary> ![image](https://user-images.githubusercontent.com/46576860/105396759-4d99a580-5c31-11eb-947d-077bd84e0958.png) </details>

- [x] praetorian_guard_perk_name <details> <summary>Click to expand</summary> 
![image](https://user-images.githubusercontent.com/46576860/105397189-c993ed80-5c31-11eb-9161-465b47a1dfa2.png)
 </details>

- [x] parthian_tactics_perk_name <details> <summary>Click to expand</summary> 
![image](https://user-images.githubusercontent.com/46576860/105397266-e8927f80-5c31-11eb-9500-e301c0a0e583.png)
 </details>

- [x] innovation_development_03_desc <details> <summary>Click to expand</summary> 
![image](https://user-images.githubusercontent.com/46576860/105397805-91d97580-5c32-11eb-9ef5-66130f62abe3.png)
 </details>

- [x] innovation_cranes_desc <details> <summary>Click to expand</summary> 
![image](https://user-images.githubusercontent.com/46576860/105398067-f09eef00-5c32-11eb-83be-418d086ada6e.png)
 </details>

- [x] blood_legacy_5_name <details> <summary>Click to expand</summary> 
![image](https://user-images.githubusercontent.com/46576860/105398469-758a0880-5c33-11eb-8f0b-8bf5b7b94b0b.png)
 </details>

- [x] game_concept_knight_desc <details> <summary>Click to expand</summary> 
![image](https://user-images.githubusercontent.com/46576860/105399095-35775580-5c34-11eb-8517-5cecf147fb95.png)
 </details>

**Comment by Gaben1025** [comment]
Changes are on this PR https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2/pull/100
