### ISSUE TITLE
Adding The Sundering/Cataclysm

### ISSUE THREAD

**Issue by Caitqua** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2#104]
I think that adding the Cataclysm is feasible, especially after seeing the abilities that we have to change the map, but it would be a LOT of work. However, I think that it would be a super cool way to radically change the dynamic of the game, as well as change both the literal and political landscape of any playthrough.

**Comment by Raged50** [comment]
map can't be changed
