### ISSUE TITLE
The Grand Mosque of Lordaeron

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2#105]
**Your mod version is:**
`-`

**What expansions do you have installed?**
`-`

**Are you using any submods/mods? If so, which?**
`-`

**Please explain your issue in as much detail as possible:**

<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46576860/105983028-2ae01480-60a9-11eb-9131-63c5addfc4c4.png)

</details>

**Steps to reproduce the issue:**
`-`

**Upload an attachment below: .zip of your save, or screenshots:**

<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46576860/105983052-33d0e600-60a9-11eb-8843-02b3b15843d0.png)

</details>

**Comment by arithon** [comment]
Can't we just replace it with the Lordaeron Palace, like the wonder in the ck2 mod?
