### ISSUE TITLE
Consistent Game Crash on the 31st of December

### ISSUE THREAD

**Issue by JukeJukestar** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2#1063]
### Your mod version is:
0.1

### What expansions do you have installed?
none

### Are you using any submods/mods? If so, which?
none

### Please explain your issue in as much detail as possible:
On some savefiles. the game will always crash on the 31st of December (last day of the year).
The year in which this occurs is random, I have had it happen in the years 593 and 678. If it happens once, its impossible to continue the campaign because it is guaranteed to always happen on the same date december 31st. You have to start a new game or reload a much older save.

### Steps to reproduce the issue:
Seemingly random, happens during a random year of the game which is different everytime. Here are two of my savefiles in which it happens.

### Upload an attachment below: .zip of your save, or screenshots:
Here are two save files where it happened: It will always happen on the next december 31st:

[GuruCrashi.zip](https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2/files/11043124/GuruCrashi.zip)

[AmaniCrashed.zip](https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2/files/11043117/AmaniCrashed.zip)

Heres one of the Crash reports:

[ck3_20230322_184418.zip](https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2/files/11043147/ck3_20230322_184418.zip)

**Comment by Rexxar4k** [comment]
Did you fix the problem?

**Comment by ercarp** [comment]
> 

This problem seemed to stem from general instability with the `1.5.0.x` version of **Crusader Kings III**. We've fixed it on our `1-8-1-update` branch which we're currently applying the finishing touches to before it's ready for public release.
