### ISSUE TITLE
Game crashes after December 31 649

### ISSUE THREAD

**Issue by Evolusin** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2#1078]
**Your mod version is:**   0.1 Release Alpha

**What expansions do you have installed?**  The Northern Lords

**Are you using any submods/mods? If so, which?**  None

**Please explain your issue in as much detail as possible:** Game reaches after December 31 649 

**Steps to reproduce the issue:** just let it go to December 31. On next in game day it will crash

**Upload an attachment below: .zip of your save, or screenshots:**
[save_troll.zip](https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2/files/11065125/save_troll.zip)

**Comment by JukeJukestar** [comment]
see #1063
