### ISSUE TITLE
Dynamic Factions?

### ISSUE THREAD

**Issue by Caitqua** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2#109]
What about the possibility of dynamic factions? So, instead of just Horde/Alliance, you could have the Scourge or the Burning Legion (as an example of potential factions already in established lore) also join forces with nations in the world, potentially corrupting them at the same time. 

For introducing new factions, we could have a bunch of little formable ones pop up, something like a Murloc Confederacy, the Bloodsail Buccaneers taking land and establishing an alliance with elements within Tiragarde Sound for an even larger faction devoted to piracy, etc.

**Comment by zumbak04** [comment]
Done in https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2/pull/233.
