### ISSUE TITLE
Playable unlanded characters

### ISSUE THREAD

**Issue by TheRealJekyll** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2#1090]
**Describe your suggestion in full detail below:**
Would be fun to play unlanded characters that have importance to the story. Like playing Jaina before the start date where she is already in theramore. Would even be cool to add in more of a class system that gives bonuses(kinda like the hunter trait, rename blade master to warrior etc). Make the unlanded characters work like how rags to riches worked for ck2

**Comment by helloruhe** [comment]
game system wont allow
