### ISSUE TITLE
History transfering

### ISSUE THREAD

**Issue by zumbak04** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2#11]
**Describe your suggestion in full detail below:**
We need some kind of script to transfer the CK2 history of provinces and titles to CK3.

**Comment by zumbak04** [comment]
Before doing it, we need to adapt titular landed titles.

**Comment by Malicos** [comment]
Titular landed titles are now adapted.

**Comment by zumbak04** [comment]
Done in #12.
