### ISSUE TITLE
Battlefront Mechanics and Potential Terrain Changing?

### ISSUE THREAD

**Issue by Caitqua** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2#110]
These mechanics would be tied to existing factions (namely the Horde and Alliance), and potential event chains that form in locations where their borders touch and they are NOT at war (or maybe they are, and we could have a slightly different event chain tied to that as well, or even tied to a quest system). These events could be tied to border skirmishes and extracting resources from the land (like in Ashenvale when the Horde decided to clear-cut the forests and fight the Night Elves at the same time), and could visually change the terrain and confer permanent modifiers to the game (either in terms of resources or in terms of opinion modifiers towards or from other races).

**Comment by zumbak04** [comment]
Have to say you can't change the terrain. Border conflicts are fine but I would say it's not that needed. Shouldn't be tied to the Horde and Alliance, it's a usual thing that happens between 2 states.
