### ISSUE TITLE
Titanforged Reproduction

### ISSUE THREAD

**Issue by VespertinePetrichor** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2#1100]
## Titanforged should not reproduce biologically but rather be created.

- Assign infertile trait to all races with `flag = titanforged_class`
- Create constructible common wc building for titanforged cultures located in Mechagon, Uldum, Mogu'shan Vault and Ulduar.
  - Enabled decision to create more titanforged characters as courtiers on a cooldown.
    - Building level decreases cooldown, increases chance of creating more courtiers (e.g. random number between x and y) and courtiers with better stats or traits.3
  - Multiple buildings do not stack, but may reduce the cost of cultural MaA recruitment and upkeep.

**Comment by Donekulda** [comment]
By located is by that meant that its location locked or just all cultures that are present in those locations ?
