### ISSUE TITLE
Unions don't inherit

### ISSUE THREAD

**Issue by Maryffodil** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2#1121]
**Your mod version is:**
Github 1.8.1 latest
**What expansions do you have installed?**
All but not activated northern lords
**Are you using any submods/mods? If so, which?**
No
**Please explain your issue in as much detail as possible:**
Unions don't inherit and become basically defunct on leader death, the regent stays and the members do but nobody can join and nobody can become the leader because the dead person is still leader

E.g. After backhand dies the horde is kinda dead because of this bug and I have to make a new union for each new ruler after the death of previous one
**Steps to reproduce the issue:**
Have any union and the leader die

**Upload an attachment below: .zip of your save, or screenshots:**
![image](https://user-images.githubusercontent.com/130665638/231756624-64b49d5f-57a7-4973-998e-648d6b82ac4a.png)
![image-1](https://user-images.githubusercontent.com/130665638/231756637-c3d3fe17-f982-4824-adc6-6af21845ae83.png)
![image-2](https://user-images.githubusercontent.com/130665638/231756644-e239327c-7417-4a90-b13c-56ee0c7e4587.png)

**Comment by CantTouchThisJinTao** [comment]
Doesn't seem to be an issue in current 1-8-1 branch.
