### ISSUE TITLE
Lordamere duchy building/capital wrong county

### ISSUE THREAD

**Issue by CantTouchThisJinTao** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2#1143]
**Your mod version is:** Master

**What expansions do you have installed?** All

**Are you using any submods/mods? If so, which?** N/A

**Please explain your issue in as much detail as possible:** In the duchy of Lordamere the capital of the duchy is Undernelly but the duchy building slot is on the Dawning Isles county.

**Steps to reproduce the issue:**

**Upload an attachment below: .zip of your save, or screenshots:**

![lordamereduchycapital](https://user-images.githubusercontent.com/86842532/233853004-8cccd485-504a-4027-9728-12df5a102d98.png)

**Comment by ValianBlue** [comment]
_Moving this to #342._
