### ISSUE TITLE
Undeadify ability

### ISSUE THREAD

**Issue by monsterius** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2#1164]
**Describe your suggestion in full detail below:**
I suggest adding an ability to convert vassals/court members into Undead for if not all Necro factions but at least for Scourge. Right now it just doesn’t make much sense having half of your minions (I mean when playing as Scourge) as living beings when your main mission is to bring blessing of unlife to all Azeroth.

**Comment by PIKSKING** [comment]
I think this should be a costly, character interaction for Undeads.

**Comment by Raged50** [comment]
Looking at adding this after the magic system is implemented
