### ISSUE TITLE
Character Sexualities

### ISSUE THREAD

**Issue by Grekopithikos** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2#1173]
**Describe your suggestion in full detail below:**
As of right now, most characters do not have defined sexualities, which can lead to bizarre situations such as Malfurion being a homosexual despite him being in love with Tyrande.

My suggestion would be to define sexualities for characters that have explicitely showed attraction to the opposite and/or same sexes(or lack of thereof) and assign the proper sexuality for them.
For example, since Kael'thas was stated to have tried to romantically pursue Jaina, he would most likely be a heterosexual. Same thing would apply to Jaina, Arthas, Illidan and other such characters.

This [page](https://wowpedia.fandom.com/wiki/Gender_and_sexuality) could also be relevant

**Comment by zumbak04** [comment]
Oh, nice, someone already opened it. Thanks!

For the devs, I suggest you looking for characters with `add_spouse` or `set_relation_lover`, `set_relation_soulmate`. Most likely these characters are lore-ones and their sexuality can be defined by their partner.
