### ISSUE TITLE
Half-Elf culture

### ISSUE THREAD

**Issue by qarubo** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2#1185]
**Describe your suggestion in full detail below:**
I want to suggest adding half-elf ethnicity and culture(perhaps only in one or two provinces scattered in human kingdoms) this can later be used to improve blue flight dragons portraits, since they often assume half-elf form(lKalecgos for example)

**Comment by Grekopithikos** [comment]
How would you name the culture?
Human'dorei? Half'dorei? Hu'dorei? Arathor'dorei? Ara'dorei?

Isn't Kalecgos the only dragon with a half-elven visage?

**Comment by Myphicbowser** [comment]
Did you know Half-Elves are so rare that Kalecgos gets comments about his Visage? And on one hand I can count the amount of Half-Elves, and three of them were born around the time of the dark portal. I don't think a Half-Elf culture sounds right for GoA, maybe some exceptional individuals with long lived traits and a resistance to dying so you have a chance of seeing them, but they are so exceptionally rare its impossible they'd form enough population for a County.
