### ISSUE TITLE
City Terrain & Buildings

### ISSUE THREAD

**Issue by SlagartheCruel** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2#1207]
I noticed that some areas, especially human areas like Stormwind or the Capital City are often filled with farmland to make up for the fact they should be something else. Perhaps a new form of terrain can be introduced, like a Urban setting in certain areas that allows for a unique set of buildings and structures which focuses heavily on adding empire management and acting as a center for trade, commerce, and politics.

New Terrains
-**Urban** (+50% Supply Limit, +35% Development Growth, Defender Advantage +12, Combat Width 60%, Movement Speed 90%)
Ex - Durotaur, Stormwind, Stromgarde, exc
-**Complex** (-20% Supply Limit,+5% Development Growth, +25 Danger, 70% Movement Speed, 50% Combat Width, +16 Defender Advantage)
Ex - Gnomeregan, Throne of Thunder, Blackjack Mountain

Buildings
-**Apartments**
Primarily provides money, is cheap and faster to build than other city buildings
-**Tavern**
Provides money and popular opinion.
Allows owner to visit bar for special events, gain friends, go drinking, exc
-**Bank**
Provides huge holding taxes boost, and empire wide money boons
Allows owner to take out a loan from the bank
-**Auction House**
Provides huge holding taxes boost, bigger than bank's, but only provides duchy wide effects.
Allows owner to explore auction house to sell unwanted artifacts or buy new ones
-**District**
Provides massive money boost, provides significant development growth benefits
-**Armory**
Far stronger version of the blacksmith for buildings
-**City Temple**
Provides varied effects such as money, development, popular support, exc. Primarily provides piety.
-**City Market**
Provides massive boost to money and development growth
Allows owner to visit to buy various quality artifacts, with variety depending on the building level
-Level 1-2: Visiting a baker
-Level 3-4: Visiting a Smith
-Level 5-6: Visiting an Engineer
-Level 7-8: Visiting an Enchanter/Scribe
-**Entertainment**
Provides minor money and popular opinion boost, significant popular opinion boost realm wide
Greatly cheapens grand tournaments
-**Civic Square**
Provides significant boosts to cheapening building cost and time, popular opinion boost, and defender advantage
Allows owner to make a big speech to boost popular support and give diplomacy buffs if successful
-**Canals**
Massive development boosts
-**Roads**
Boosts development and money
-**Estate**
Provides minor benefits
Allows owner to retreat to estate to hone skills or relieve stress, giving big and permanent boosts while leaving the country in the temporary care of a regent. However, being in a estate can also make one more vulnerable to intrigue.
-**Statue**
Provides huge prestige and renown boosts
Allows owner to make a big speech in front of statue to either push personal glory or impress on higher nobility
-**Walls**
Basic but powerful defensive buildings
-**Jail**
Increases dread for owner, and reduces tyranny gain. Gives some minor economic boons
Owner can recruit or forcefully conscript prisoners to become loyal or disloyal courtiers with strong hooks
Opens a Warden minor title which makes escaping from owner's dungeons more difficult (or easier)
-**Bestiary**
Increases prestige and renown, give minor economic benefits, gives minor aerial and mounted benefits
Unlocks activity to hunt for animals to send to bestiary, giving temporary but powerful benefits related to Bestiary's passive boons
-**Shadowy District**
A slums inspired building which gives decent income, but hampers development and holding taxes
Unlocks the several intrigue abilities to kidnap, murder in dark alley, instigate riot to kill someone, and to summon a demon for cursed boons
-**Campus**
Gives huge culture fascination boons
-**Magical District**
Gives decent culture fascination boons, but not as powerful as campus, provides big boons for casters
Owner can interact with mages for some manner of myriad effect
-**Port (Coastal Only)**
Much more powerful version of normal port

Although urban would be powerful money makers, as they should be, they are also more vulnerable. Mechanically, if an urban area is captured, there is a high chance buildings at any level can be destroyed, but there would also be a chance at a riot if popular opinion goes low enough. Much like the Stormwind riot, a city wide riot is an event which can happen if popular opinion is lowered, this happens due to events which specifically effects urban cities only which reduce popular opinion, or due to events. Riots can kill, injure, or traumatize characters and makes cities useless for a few months if not years.

All city buildings (with an exception of apartments) are inherently expensive, and all level 8 buildings will produce renown for its owners in some capacity. Cities, while very good, also are meant to have a lot of dangers and can be counter-productive if handed by only a smaller realm.

**Comment by helloruhe** [comment]
closed bc of similar issue
