### ISSUE TITLE
Reduce, Remove, or Overhaul the Instant Death Events

### ISSUE THREAD

**Issue by SlagartheCruel** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2#1221]
Playing a few times and I've noticed that nearly everyone is afflicted by a few very grim and sudden instant death events, usually with a seeded survival rate of 20% at best. There are not usual events either, these events are usually meant to be freak accidents I think, but a lot of these freak accidents are wreaking havoc all over the place and are not very rare. There is a mod I've seen released that does help with it, but it is really annoying that a lore character dies off because they spontaneously combusted, or fell down some stairs, or drowned.

Immortal characters also especially get afflicted by these events, especially stroke events, to a point where nearly half the immortal characters in what should be the mid game are disabled. Courtiers with inspirations from long lived races, satyrs specifically, will just appear be unable to be patronized because all of them are incapable.

An option to remove or just reduce the likelihood of these events firing, especially for long lived characters would be certainly nice to have.

**Comment by Raged50** [comment]
Can you link the mod for me? I'll have a look

**Comment by SlagartheCruel** [comment]
After some fruitless searching, I couldn't find the specific one, but there is a mod which was similar enough
https://steamcommunity.com/sharedfiles/filedetails/?id=3018207099&searchtext=harm_eventsdfsd

**Comment by Myphicbowser** [comment]
As this is a base game issue, you have a setting for it. In the options there is a Random harm setting, if you set that to safe then characters won't become incapable randomly. Everyone complains about this vanilla feature, so the setting to disable it is nice to have. Especially since it happens to **everyone** eventually, unless you disable it in the game rules.
