### ISSUE TITLE
Undead Cultures have too many living people

### ISSUE THREAD

**Issue by Devlerbat** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2#1223]
I have noticed a lot of non-undead characters with cultures that have an undead heritage. For the Damned culture this isn't as big of a deal since the cult of the damned has plenty of living members, but often the game winds up with the majority of the Forsaken characters not having the undead trait. Is there a way to increase the chance that when the game spawns a character of undead culture that they would have the undead trait?

**Comment by edmund-h** [comment]
fixed in forsaken events PR and also some fixes by @sumankun
