### ISSUE TITLE
Saurok missing body 

### ISSUE THREAD

**Issue by Lordmitch2** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2#1232]
**Your mod version is:**
0.3.2 Release Alpha
**What expansions do you have installed?**
All
**Are you using any submods/mods? If so, which?**
Music Submod
**Please explain your issue in as much detail as possible:**
Saurok are missing part of their bodies. 
**Steps to reproduce the issue:**

**Upload an attachment below: .zip of your save, or screenshots:**
![image](https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2/assets/47829580/412fbf9a-fe13-4f15-961c-6097a68351da)

**Comment by helloruhe** [comment]
just happens with static races
