### ISSUE TITLE
Event Idea for Education of Important characters 

### ISSUE THREAD

**Issue by ulricee** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2#124]
**Describe your suggestion in full detail below:**

Knowing the ck2 class system would most likely be added sonner or later I wanted to introduce idea's for what type of education historical characters.

Exemple for important characters:

Jaina:
In lore, her mother had to convince her father to eventually have her learn at Dalaran after her magical potential was discovered post second war, an event could be made for Daelin to accept her wife request (canon), leave her under the Tidesages tutelage (possible old god corruption) or doing another class all together (generic choice).

Anyone can add ideas for special education of characters bellow if you wish.

**Comment by zumbak04** [comment]
I would rather make it a generic event that may happen for everyone. Sounds like an interesting situation.
