### ISSUE TITLE
Implement Paladins as a Unique MAA for the Human Kingdoms

### ISSUE THREAD

**Issue by John0-droid** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2#1240]
**Describe your suggestion in full detail below:**

Paladins were first created by Archbishop Alonsus Faol to protect the Alliance of Lordaeron in the Second War.
They became some of the Alliance's most elite troops and were instrumental in beating back the First Horde from Lordaeron.
[](https://wowwiki-archive.fandom.com/wiki/Paladin)  [](https://wowwiki-archive.fandom.com/wiki/Alonsus_Faol)

As most other races have their own unique men-at-arms (even the naga have their own heavy infantry), it is only appropriate that humans should be able to recruit these holy knights into their armies. Since they are explicitly defined as "holy knights" in the wow lore, it would be most accurate to implement them as Heavy Cavalry rather than heavy infantry. To show their bonuses against the unholy forces in the Scourge, perhaps consider giving them an additional counter against skirmishers (to represent the Scourge ghouls).

Additionally, it is important to switch the "order knights" in the Silver Hand holy order to especially strong versions of this MAA upon their creation, seeing as this group represented the very first Paladins under Uther the Lightbringer. Thank you for your time.

![57cd288a-f7a3-4dcd-bb71-113e9c7e4c5f](https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2/assets/80145462/bab01889-3b71-4b61-9f0e-448f52a352f3)

**Comment by ElMariuso** [comment]
Already planned
