### ISSUE TITLE
Infirm Trait on Long Lived Races

### ISSUE THREAD

**Issue by PearlForger** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2#1241]
[](url)
**Your mod version is:**

**1.10.2**

**What expansions do you have installed?**

I have all expansions installed. The new legacy of Persia DLC I have disabled.

**Are you using any submods/mods? If so, which?**

None

**Please explain your issue in as much detail as possible:**

Characters from older lived races (Dragons, Elves, Dwarves, Gnomes, Naga, Aqir, etc.) all pretty quickly get the infirm trait. From my observations, it seems that the older the character is, the faster that they will get the infirm trait. Playing as a Naga, the infirm trait severely limits the effectiveness of my council members because their stats are ruined pretty early on in the game. The same thing happens to my councilors when playing as a Dragon or an Aqir. What makes this stat-reduction issue even worse is that infirm characters become depressed (get the melancholic trait). Personally, I believe that the best solution to this problem is simply removing the older races' ability to get the infirm trait in the first place. 

**Steps to reproduce the issue:**

Simply run the mod for a while and you will notice this issue when looking at different characters from long-lived races.

**Upload an attachment below: .zip of your save, or screenshots:**

These screenshots are taken from 4 different games with different game years.

![20231119140241_1](https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2/assets/124048741/6df4fa85-70ee-4ed4-a047-6a50a801da0a)
![20231119140249_1](https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2/assets/124048741/351ad680-5419-4a1f-824d-9b9f6898ef22)
![20231119140308_1](https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2/assets/124048741/c91153d6-d987-4f70-8720-1e1c335413c6)
![20231119140401_1](https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2/assets/124048741/976e3b19-93ed-4b50-9264-6b6225a48668)
![20231119140446_1](https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2/assets/124048741/57e77e69-c510-43f7-a927-479edd4b14e1)
![20231119140939_1](https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2/assets/124048741/62651fed-6581-4a00-8e7f-3c118994e6b9)
![20231119141336_1](https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2/assets/124048741/1086690e-bb7d-4fdc-904d-4d578cd14d6f)
![20231119141417_1](https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2/assets/124048741/439387d1-6066-435f-94d3-5ef97d711854)
![20231119141440_1](https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2/assets/124048741/90afe53c-e2db-4004-b55f-4e003f7877aa)
![20231119141504_1](https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2/assets/124048741/e806ca67-d9e3-4986-9c89-cb6c8b8cea31)
![20231119142157_1](https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2/assets/124048741/5241980b-bdec-4905-a3f4-56c88ff6d69c)
![20231119142208_1](https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2/assets/124048741/06a33409-58a9-427c-ae0d-f37096a78275)
![20231119142231_1](https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2/assets/124048741/be54ba2a-ab8f-4c3f-9917-3ea885374526)
![20231119142345_1](https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2/assets/124048741/2e9aeea5-5727-4c60-804c-1367fed7412b)
![20231119143524_1](https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2/assets/124048741/6c3cfe80-95a7-440a-8d92-4c5743cc0c55)

**Comment by edmund-h** [comment]
added high priority because the community is very concerned about this and a lot of us are too

**Comment by edmund-h** [comment]
PR for a fix is coming soon following developer testing

**Comment by edmund-h** [comment]
[working branch here](https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2/tree/infirm-issue-1241-fix)

**Comment by edmund-h** [comment]
linked the PR, just need code review and testing and we should be gravy!
