### ISSUE TITLE
Suggestion: make it less likely to die in storms at sea

### ISSUE THREAD

**Issue by JamarcusRue** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2#1252]
**Describe your suggestion in full detail below:**

Given the size of the map, rulers travel overseas a lot for hunts, marriages, tournaments, wars, and so forth. 

Lots of characters die at sea. It is something of a buzzkill to see both Rhonin and Vereesa all die from storms at sea on the same day. If you disable the T&T "Dangers of the Deep" event (and similar events), greatly decrease their frequency, or reduce overall danger of sea zones, then this wouldn't happen as often.

**Comment by edmund-h** [comment]
ok since there was no update on this, i would like to point out that @sumankun provided a partial fix for this somewhere, but it only works up until game year ~608 or so
