### ISSUE TITLE
Clan Governments for more Cultures

### ISSUE THREAD

**Issue by Myphicbowser** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2#1275]
I think the clan government type should be available for Centaur, Quillboar, and Troll Cultures

Ideally I think that it should be allowed for ALL cultures to form a Clan instead of a Feudal government, since it adds more player options and a lot of work went into making the clan government generic and not even aligned with the Horde itself, however I understand some people wouldn't agree with that.

**Comment by Myphicbowser** [comment]
Adding onto this, Ogres should ALSO have it, forgot to mention them directly.

**Comment by edmund-h** [comment]
fixed in #1285
