### ISSUE TITLE
Change Naga Government Type

### ISSUE THREAD

**Issue by Myphicbowser** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2#1276]
While I do think that the Eldritch Government is fun, I don't believe it fits the Naga. The Naga are not a hivemind or really anything outside the norm psychologically. They are strict adherents to Aszhara and the worship of her yes, but they are still people, many now Born Naga instead of originally turned into them. I don't think that Eldritch fits them, and I hope this gets discussed and potentially changed.

I believe that Feudal is the better choice for them, however arguments can be made for Clan if it's desired.

**Comment by Raged50** [comment]
I think the easiest solution here is to remove the void being trait being automatically assigned to all Naga creatures, and when the magic system is implemented if anyone goes down the void path they can become eldritch gov

**Comment by edmund-h** [comment]
completed with merge of PR #1286
