### ISSUE TITLE
Holy sites on Broken Isles

### ISSUE THREAD

**Issue by helloruhe** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2#1277]
From [Reddit](https://www.reddit.com/r/GuardiansOfAzeroth/comments/18jg7o5/holy_sites/)

> I wish there would be more holy sites on the broken isles. for example the drogbar religion doesnt have any holy sites in the drogbar lands but in northrend instead, also sargerite religion should have a holy site in the TOMB OF SARGERAS :D you just cant do much religion wise with most of the characters on the isles

**Comment by Raged50** [comment]
Any other religions besides drogbar and the tomb of sargeras?

**Comment by helloruhe** [comment]
can't think of anything else tbh

**Comment by Grekopithikos** [comment]
The Arkkoroc faith could use its own holy sites, right now it uses murloc ones and the one in Arkkoran has its effects copypasted from another one.

**Comment by helloruhe** [comment]
okay, anything else anyone suggest we can just make a list for it
