### ISSUE TITLE
Magic Secrecy

### ISSUE THREAD

**Issue by edmund-h** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2#1307]
We will use one of four approaches in order to deal with illegal magic: 

1. Every character's magic progression is completely open information, you can see exactly what magic everyone uses at all times and put them in jail if you so choose. Choosing an illegal magic to progress instantly makes you a criminal. Classes not implemented until a later date. 
2. You can see any LEGAL magic that characters use at all times and if anyone has a secret illegal magic progression that is revealed by a scheme or interaction, everyone can see that forever (you can always see this info for yourself and your immediate family). Classes not implemented until a later date.
3. Everyone has one of four meta-class lifestyle traits (fighter, agent, caster, priest) that everyone can see and everyone can see how powerful they are based on overall magic/ability progression, but exactly what spells/abilities aren't known unless you interact with or scheme them. When illegal magic is revealed, they get an "illegal magic user" trait for their religion. Exact classes may be implemented later. **will be replaced by magical power stat.**
4. You can never see what kind of magic or abilities anyone uses unless it is revealed by interaction or scheme. Classes arent a visible trait but a dynamic title based on magic progression you can see in a special UI when you have the correct knowledge about or relationship with a character (you can always see this info for yourself and your immediate family). Classes per se will never be implemented unless the community demands it.

This task will be updated once we have asked the Patreons about which one will be used, so far consensus has seemed to bend towards #2

**Comment by robmart** [comment]
Closing, as this has been completed for some time
