### ISSUE TITLE
New Buildings

### ISSUE THREAD

**Issue by Gaben1025** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2#133]
**Describe your suggestion in full detail below:**

- We should add new buildings to the mod
- See #670  for further ideas

**Comment by Gaben1025** [comment]
Similar to Imperator Rome 2.0 update, we should add a Settlement/City/Metropolis upgrade slot to the mod, based on development.

**Comment by zumbak04** [comment]
2 types of building chains we need:
- [ ] Buildings that buff casters
- [ ] Buildings that buff aerial units

**Comment by Gaben1025** [comment]
> Building chains we need:
> 
> * [ ]  Casters building chain, 8 levels
> * [ ]  Aerial building chain, 8 levels
> * [ ]  Casters duchy building chain. 3 levels
>   
>   * May give learning
> * [ ]  Aerial duchy building chain. 3 levels

What will be the difference between normal and duchy buildings?
