### ISSUE TITLE
Out of screen logo during loading with 21:9 scaling

### ISSUE THREAD

**Issue by starscrm** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2#1335]
**Your mod version is:**
0.4.1 Release Alpha

**What expansions do you have installed?**
All

**Are you using any submods/mods? If so, which?**
None

**Please explain your issue in as much detail as possible:**
During loading to game, logo of mod located out of screen if set resolution, match to 21:9 scaling (in my case 3440x1440)

**Steps to reproduce the issue:**
1. Enter to game. 
2. In graphic setting set resolution, match to 21:9 scaling
3. Re-enter to game

**Upload an attachment below: .zip of your save, or screenshots:**
https://imgur.com/a/DSuHrg2

**Comment by helloruhe** [comment]
Not sure if we can fix this, because the size of the loading screen is constant. It’s not meant for this resolution
