### ISSUE TITLE
Add a player-only element to the interracial marriage rule

### ISSUE THREAD

**Issue by KodyFFy** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2#1361]
**Describe your suggestion in full detail below:**
I think it would be nice to add the option of free interracial marriages only for the player or make it possible to choose races that can marry in order to avoid the appearance of characters without a model and strange marriages from AI. Thanks for your attention.

**Comment by helloruhe** [comment]
Hi Kody, while we appreciate your suggestion, please utilize the new system in outlined the ck3-suggestions channel pins to submit your idea so the community can vote on it. Thanks
