### ISSUE TITLE
Warcraft music/sfx

### ISSUE THREAD

**Issue by Volken** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2#137]
- Add popular music from Warcraft titles
- Automatically play specific tracks depending on player race
- Automatically play specific tracks depending on player actions (war, peace, special events)
- Replace most common CK3 SFX with recognizable Warcraft SFX
- Add Warcraft SFX for special events

**Comment by helloruhe** [comment]
done
