### ISSUE TITLE
Eredar cant build Dark Portal

### ISSUE THREAD

**Issue by Tatertot321** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2#1379]
**Your mod version is:**
Latest
**What expansions do you have installed?**
All
**Are you using any submods/mods? If so, which?**
No
**Please explain your issue in as much detail as possible:**
Eredar cannot rebuild the Dark Portal
**Steps to reproduce the issue:**
Be Eredar. Take Dark Portal. Can't rebuild
**Upload an attachment below: .zip of your save, or screenshots:**

**Comment by Raged50** [comment]
Idk why this didn't appear on discord as a bug report but I will look into this

**Comment by Raged50** [comment]
fixed in 1.12 update
