### ISSUE TITLE
Support Request - Crash on Boot

### ISSUE THREAD

**Issue by Siveen** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2#1388]
**What problem are you encountering during launching the mod?**
Crash on Boot.
[exception.txt](https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2/files/15155153/exception.txt)
[debug.log](https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2/files/15155154/debug.log)
[error.log](https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2/files/15155155/error.log)

**Comment by Raged50** [comment]
referred to discord bug report system
