### ISSUE TITLE
Missing Localization - building_type_teldrassil_corrupted

### ISSUE THREAD

**Issue by Rimaka94** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2#1428]
**Mod version:**
dev

**Are you using any submods/mods? If so, which?**
Main Menu Debug

**Please explain your issue in as much detail as possible:**
Teldrassil special building in Darnassus is missing building type localization: **building_type_teldrassil_corrupted**

Note: Though the key says 'corrupted', the value should just be 'Teldrassil' to match other special buildings.

**Upload screenshots of the problem localization:**
![image](https://github.com/user-attachments/assets/71cd4711-b700-448c-95b9-cd725a38fc2e)

**Comment by helloruhe** [comment]
already fdix
