### ISSUE TITLE
Less Likely Interracial Marriages

### ISSUE THREAD

**Issue by zumbak04** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2#144]
**Describe your suggestion in full detail below:**
We should make interracial marriages to be less likely to preserve the looks of existing races.

**Comment by ercarp** [comment]
I agree. Half-breeds are fun to play around with but the races will be unrecognizable in 100 years if the races keep marrying outside of their own races. It should still happen to a degree, of course.
