### ISSUE TITLE
Forsaken Flavor 1

### ISSUE THREAD

**Issue by helloruhe** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2#1445]
A Method for The Forsaken being unique in some way, perhaps by giving Sylvanas Val'kyr, that make them not as reliant on the Dark Frenzy system, as The Forsaken are not Scourge and thus have no intention on continuous and unending raiding and conquest. It just seems out of character to be punished when playing tall/passively as The Forsaken.
Linked to Suggestion #3 on discord

**Comment by robmart** [comment]
Duplicate of #1358
