### ISSUE TITLE
Bronzebeard ages should be adjusted to match lore

### ISSUE THREAD

**Issue by ercarp** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2#145]
**Describe your suggestion in full detail below:**

According to the [Warcraft III: Reign of Chaos Game Manual](https://wow.gamepedia.com/Warcraft_III:_Reign_of_Chaos_Game_Manual), which is canon, Muradin was 221 years old during the Third War. Using CK3's dating system _(King's Calendar minus 9 years)_, this would make his new birth year **382**. Currently, it's set to 511.

Since Muradin is the middle brother of the Bronzebeards, with Magni being the oldest and Brann the youngest, their birth years would have to be adjusted accordingly:

- Magni must have been born in the year 381 or earlier (currently 486).
- Brann must have been born in the year 383 or later (currently 523).

**Comment by zumbak04** [comment]
So he's actually older... I see.
