### ISSUE TITLE
'Sacrificed to the Gods' execution method is not using 'send to Twisting Nether' bypass on Demons

### ISSUE THREAD

**Issue by Rimaka94** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2#1503]
**Your mod version is:**
\/dev

**What expansions do you have installed?**
All

**Are you using any submods/mods? If so, which?**
Main Menu Debug

**Please explain your issue in as much detail as possible:**
Religions that use the **Human Sacrifice** tenet makes it so the 'Sacrifice' method is used when you go to Execute a prisoner. When Sacrifice is used as the Execution Method, the 'return to Twisting Nether' code is not being called, so the demon's death reason is "Was sacrificed to your gods on Date at age ???".

**Steps to reproduce the issue:**
As a character of a faith with the **Human Sacrifice** tenet (Maldraxxi for example, Raven Hill start 603), imprison a demon and execute them with the 'Sacrifice' method selected. The demon will not be sent to the Twisting Nether, they will not gain the associated trait, and their death reason will show as 'sacrificed to the gods'.

**Upload an attachment below: .zip of your save, or screenshots:**
![image](https://github.com/user-attachments/assets/64ffc315-e04c-4eda-8162-0a630900d729)
![image](https://github.com/user-attachments/assets/7970e65c-6f30-49a4-918a-2b8c09fd5a20)

**Comment by helloruhe** [comment]
Intended, but fixed the loc to show correctly
