### ISSUE TITLE
Repeated pregnancies

### ISSUE THREAD

**Issue by edmund-h** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2#1531]
I am playing as Haleh, a historical blue dragon character. in my previous game as her I had multiple children with my various husbands with no issues. This time I am repeatedly getting pregnant when I am already pregnant and not having any children. 

Easily reproduceable: 

- Play as Haleh
- Marry 2 or more husbands besides Malygos
- Watch as repeated pregnancies roll in (occurrence is somewhere between 25-75% every 3 months)

**Comment by sumankun** [comment]
From what i see someone accidentally deleted some triggers during the last dlc update in pregancy event files. Goa code stops the pregnancies with high chance for dragon/elves. But because custom trigger deleted, notification about pregnancy comes, even it is interrupted

**Comment by helloruhe** [comment]
ty mayonez
