### ISSUE TITLE
Culture Divergence lets you pick every heritage

### ISSUE THREAD

**Issue by Grekopithikos** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2#1545]
**Issue Description:**
When diverging a culture you are given the options to pick from every heritage that exists instead of the one you have.

**How To Reproduce:**
Go to your character's culture tab and click "Diverge Culture" then scroll down.

**Screenshots:**
![Στιγμιότυπο οθόνης (2)](https://github.com/user-attachments/assets/b0f76641-99ce-4f58-b652-2a447065c1dc)
![2024-10-24 (2)](https://github.com/user-attachments/assets/d08489aa-2ee0-4385-96ed-3f8d21610900)

**Game Files:**

**Comment by Rimaka94** [comment]
just a heads up - I saw this prior to the RtP patch as well

**Comment by helloruhe** [comment]
not a bug and event if it was i cant fix it anyway 
![image](https://github.com/user-attachments/assets/7450abae-e674-48d4-a865-5dc81dfc3bfb)
