### ISSUE TITLE
Static Models - Some events and all councilors for static models have a long fleshy model on top

### ISSUE THREAD

**Issue by Rimaka94** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2#1548]
**Issue Description:**
Since the RtP dev merge, I've been seeing a stretched fleshy model on top of or going through the static model in a lot of events containing them. There seems to be some cases where it does not appear, as can be seen in screenshots. The easiest way to reproduce appears to be checking the statics in the Council view.

May be related to certain animations? I cannot reproduce this in the Barbershop scenes menu though, so that may be incorrect.

**How To Reproduce:**
Play as a character with a static model. Check the Council view, assign roles as needed. Wait for events to pop.

**Screenshots:**
![image](https://github.com/user-attachments/assets/312a7197-4fc2-45fe-a1d0-3f22363b3cd6)
![image](https://github.com/user-attachments/assets/1dfd6e58-a50b-4ff1-a317-a2b82a44d1aa)
![image](https://github.com/user-attachments/assets/9749f405-5111-4f02-b237-de11c3b3c09d)
![image](https://github.com/user-attachments/assets/cd3d79d7-b9cb-4779-883b-4dac9d5f2f7c)
![image](https://github.com/user-attachments/assets/6328d753-12e7-42a5-8be4-cf6c6643c77f)
![image](https://github.com/user-attachments/assets/5364571e-6b59-4737-ba76-e62e65db03c0)
![image](https://github.com/user-attachments/assets/5719e043-c8a5-48db-89ed-250c50e7df2b)

**Game Files:**

**Comment by helloruhe** [comment]
cant fix because my mommy said no
