### ISSUE TITLE
Ahistorical elves affected by aging differently

### ISSUE THREAD

**Issue by ercarp** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2#155]
In this context, ahistorical refers to characters without a Historical ID (i.e. generated randomly by the game as opposed to having a user-generated historical entry).

**Exhibit A**: Duchess Talihayna, 581 years old, **no Historical ID**. Looks about a thousand years old.

<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/78575425/108154301-4d33e380-70e5-11eb-87a9-f66bd7f0a4b1.png)

</details>

**Exhibit B**: Lana'thel, also 581 years old, **has a Historical ID**. Looks to be in her twenties, maybe thirties.

<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/78575425/108154407-7b192800-70e5-11eb-81fb-7aeca944fa98.png)

</details>

Removing the `immortal_age=18` trait from Lana'thel (left over from CK2 import) does not fix this issue.

**Comment by zumbak04** [comment]
It fixes after one day passes.

**Comment by ercarp** [comment]
> 
> 
> It fixes after one day passes.

Huh, so it seems. Closing this one then.
