### ISSUE TITLE
Murloc Sex Scenes

### ISSUE THREAD

**Issue by zumbak04** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2#159]
**Describe your suggestion in full detail below:**
We MUST add custom descriptions for murlocs here.
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46384992/108233489-447ef400-715d-11eb-90ce-b8acfb304296.png)

</details>

**Comment by ercarp** [comment]
I feel like this should have critical priority.

**Comment by zumbak04** [comment]
> I feel like this should have critical priority.

I have a philosophy. The most pleased things should be the last.

**Comment by SolTsuki** [comment]
I've been checking the whole sex scene thing on the game and... it seems like it's halfway implemented in the vanilla game, I don't even know how to trigger a sex scene (if you check a few files feels like it is related to the seduce scheme). I'll try one day, when I have the heart to implement an entire sex event system.
