### ISSUE TITLE
Red-eyed Sylvanas and Nathanos

### ISSUE THREAD

**Issue by zumbak04** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2#170]
**Describe your suggestion in full detail below:**
Make Sylvanas and Nathanos red-eyed.
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46384992/108561713-26112800-7318-11eb-8f29-0a8a11135c7a.png)

</details>

**Comment by ercarp** [comment]
Nathanos and Sylvanas need completely scripted undead appearances. I've already made these, we just need to add an exception to `being_undead` so it doesn't affect their appearances.

### Nathanos Undead Colors

<details><summary>Click to expand</summary>


```
Hair
x = 0.243
y = 0.969

Eyes
x = 0.027
y = 0.498

Skin
x = 0.604
y = 0.298
```

</details>

### Sylvanas Undead Colors

<details><summary>Click to expand</summary>


```
Hair
x = 0.075
y = 0.051

Eyes
x = 0.024
y = 0.612

Skin
x = 0.835
y = 0.200
```

</details>

**Comment by zumbak04** [comment]
Done in https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2/pull/156/commits/8d642d47a98cea4ace5fcb8a71c4788e2bc71813.
