### ISSUE TITLE
Custom Born Dates

### ISSUE THREAD

**Issue by zumbak04** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2#175]
**Describe your suggestion in full detail below:**
Try to tweak the interface and localization a bit to show that Tyrande and other really old characters were born a long time ago.
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46384992/108601969-f5cd9600-73b8-11eb-92d1-bcd503ff16d6.png)

</details>
I advise using some kind of character variable alternative to the character's real age.

**Comment by MemeWizard** [comment]
> I advise using some kind of character variable alternative to the character's real age.

Variables are deleted after character's death

I suggest to just change localisation and show age and birth date of characters born before 1.1.10 as "???"

**Comment by zumbak04** [comment]
> Variables are deleted after character's death

> I suggest to just change localisation and show age and birth date of characters born before 1.1.10 as "???"

Global variables not.

But the last also works for me.

**Comment by MemeWizard** [comment]
> Global variables not.

AFAIK, global variables also not shown in localisation atm

**Comment by ercarp** [comment]
Alternatively, although it's a much more daunting task, we could just increase the playable time period to 25,000 - 30,000 years or so. This will require updating a lot of date entries in the files, but maybe it would be better in the long run.

**Comment by robmart** [comment]
> 
> 
> Alternatively, although it's a much more daunting task, we could just increase the playable time period to 25,000 - 30,000 years or so. This will require updating a lot of date entries in the files, but maybe it would be better in the long run.

Max date is apparently 9999/12/31
