### ISSUE TITLE
Nathanos Is Gone

### ISSUE THREAD

**Issue by ercarp** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2#184]
**Your mod branch is:**
`dna-1`

**Please explain your issue in as much detail as possible:**

After we added the `being_undead_nathanos` portrait modifier to the **_Undead_** trait, his character has disappeared from the game.

**Steps to reproduce the issue:**
1. Load up any bookmark and try to find "Nathanos" using the Character Search.

**Upload relevant attachments below:**

History entry for Nathanos in `60000_63000_lordaeronian.txt`:

<details><summary>Click to expand</summary>

```
#Nathanos Blightcaller
60081={
	name=Nathanos
	dynasty=30020
	dna=nathanos_marris_dna
	culture=lordaeronian religion=holy_light
	martial=8 diplomacy=6 stewardship=6 intrigue=6 learning=4
	trait=education_martial_4
	trait=unyielding_defender
	trait=diligent trait=brave trait=chaste trait=content 
	disallow_random_traits=yes
	father=60079	#Arthur
	mother=60080	#Selwyn
	558.7.27={ birth=yes trait=creature_human }
	558.7.27 = {
		effect = {
			add_character_flag = has_scripted_appearance
			add_character_flag = nathanos_flag
		}
	}
	578.1.1={
		employer=42002 #Anasterian
		trait=class_hunter_6
		trait=intellect_good_1
		# Rumors... you know
		effect={
			set_relation_lover = character:42076 #Sylvanas
		}
	}
	604.1.1={
		trait=being_undead
		religion=death_god
		trait=sadistic #The Scourge corrupted him
		give_nickname=nick_the_blightcaller
		# effect={ set_graphical_culture = human_undead }
	}
	605.6.5={
		religion=forsaken_cult
		culture=forsaken
		employer=42076 # Sylvanas
	}
	630.1.1={ death=yes }
}
```

</details>

**Screenshot of Character Finder in 583 bookmark**:

<details><summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/78575425/108612829-c3418e80-73f4-11eb-81fa-a07a2c0ad162.png)

</details>

**Screenshot of Character Finder in 603 bookmark**:

<details><summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/78575425/108612862-069bfd00-73f5-11eb-814d-1c4fca055db5.png)

</details>

**Screenshot of Character Finder in 605 bookmark**:

<details><summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/78575425/108612897-419e3080-73f5-11eb-9415-7d99759de715.png)

</details>

As you can see, **Nathanos Marris** (AKA Blightcaller) is not in any of them. All it's able to find are some lowborn characters with the same name.

**Comment by zumbak04** [comment]
Fixed!
