### ISSUE TITLE
Lore-important characters should not be affected by Beauty/Ugly/Prowess

### ISSUE THREAD

**Issue by ercarp** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2#208]
**Describe your suggestion in full detail below:**

Lore-important characters have been designed with a specific goal in mind. When I design my portraits, I take extra care to ensure they look as close as possible to whatever reference I'm using, so when their appearance is altered in-game by traits like **_Beautiful_**, it's a real bummer.

I'll use Sylvanas as an example to illustrate my point.

This is how I designer her, and it's how she's _supposed_ to look in-game:

<details><summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/78575425/109165609-693e2180-7784-11eb-9978-a8ec290e5dbf.png)

</details>

She has a narrow, high jawline as you can see.

This is what the game turns her into due to the physical modifications of **_Beautiful_**:

<details><summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/78575425/109165988-dea9f200-7784-11eb-9d8b-464f1bbab057.png)

</details>

The difference might seem subtle, but the more keen-eyed will be able to tell the difference. She has a much lower and wider jawline, and other parts of her face appear altered as well. It gives her almost a masculine look.

Maybe it's not a big deal to everyone, and maybe you prefer the **_Beautiful_** version, but that's completely besides the point I'm trying to make. As someone who spends time designing custom DNA for these characters, it's frustrating when the game alters them to look like something different from what I intended. And that's where the problem lies.

**So, my suggestion comes down to the following:**

I think characters with the `make_important_lore_character_effect = yes` effect should not be affected by any of the physical modifications of the following:

- Homely/Beautiful trait groups
- Fragile/Physical trait groups
- Muscle mass increased by Prowess stat

**Comment by zumbak04** [comment]
> * Homely/Beautiful trait groups

If you want only lore characters to not be affected, it will require new traits.

**Comment by zumbak04** [comment]
> * Fragile/Physical trait groups
> * Muscle mass increased by Prowess stat

This is addressed in 58b5fa5dff9fdff75ceefb838ee73a40306b788e.
