### ISSUE TITLE
Northsea Pirate Culture

### ISSUE THREAD

**Issue by zumbak04** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2#210]
**Describe your suggestion in full detail below:**
Northsea pirates should get different culture because they're not southern at all.
It may be either new culture or Solstice culture.

**Comment by ercarp** [comment]
Perhaps they could be based on Asian culture? Blizzard never explained which part of the world they were based on, so it could be a nice way to tie them into the game's lore a bit better. [Chinese pirates](https://en.wikipedia.org/wiki/Category:Chinese_pirates) were a thing.
