### ISSUE TITLE
High Elven Heavy Armor

### ISSUE THREAD

**Issue by zumbak04** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2#263]
**Describe your suggestion in full detail below:**
Add a high elven heavy armor for male commanders. An iconic set of spell breakers. The Blood Elf Heritage Armor is the closest representation from WoW.
https://ru.wowhead.com/transmog-set=2896/sindorei-blood-elf-heritage-armor
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46384992/112755231-d8f83400-8ff0-11eb-83f0-98625b4e9e0d.png)

</details>

**Comment by Chomski2** [comment]
High elven armos has been added on #931
