### ISSUE TITLE
The game rule for nudity has no localization

### ISSUE THREAD

**Issue by robmart** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2#268]
**Mod version:** Latest master/commit 62423767adce7d2b42e484f939589f5aec228f5f

**Are you using any submods/mods? If so, which?** None

**Please explain your issue in as much detail as possible:** The game rule displays the unlocalized variables instead of the vanilla localization.

**Upload screenshots of the problem localization:** ![Screenshot (12)](https://user-images.githubusercontent.com/4825809/113226213-e2eb9280-928f-11eb-90db-c32d99e6b820.png)

**Comment by MemeWizard** [comment]
This gamerule was removed from the game by paradox, now the player must use settings menu to turn it on or off

The mod is not yet updated to the version where this setting was deleted

**Comment by robmart** [comment]
Closed by 428909ea1f83b86845256b5c07551639276b6afc
