### ISSUE TITLE
Dire Trait for Dire Trolls

### ISSUE THREAD

**Issue by ercarp** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2#279]
**Describe your suggestion in full detail below:**

We need to add a **_Dire_** trait to represent [dire trolls](https://wowpedia.fandom.com/wiki/Dire_troll) in-game. Open to suggestions on how this would best be realized as we need to ensure it's different enough from **_Giant_**.

Current ideas:
- A stronger version of gigantism that decreases your intelligence instead of health.
- Instead of making characters simply taller, it will also increase their muscle mass.

**Comment by arithon** [comment]
And reduce the life expectancy if possible
