### ISSUE TITLE
Adaptation to 1.3.0 removed caster counter from camels

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2#282]
**Your mod version is:**
0a520e11
**What expansions do you have installed?**
All

**Are you using any submods/mods? If so, which?**
GoA

**Please explain your issue in as much detail as possible:**
Camels no longer counter casters after adaptation to 1.3

**Steps to reproduce the issue:**
`-`

**Upload an attachment below: .zip of your save, or screenshots:**

<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46576860/113576785-d87f1f00-9628-11eb-973c-755e2002e2b7.png)

</details>

**Comment by Gaben1025** [comment]
Can fix this is in regional innovations branch
