### ISSUE TITLE
Unions could be separated and made into a module

### ISSUE THREAD

**Issue by robmart** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2#288]
**Describe your suggestion in full detail below:**
The union feature from GoA is very cool, and bet that other total conversion mods could use something similar. Seperating into a module akin to Artifact or Society modules from A Way of Kings would likely benifit the CK3 comunity as a whole.

**Comment by ercarp** [comment]
@zumbak04 did all the work on that module so it's up to him, but I agree.
