### ISSUE TITLE
Lothar_Lothair

### ISSUE THREAD

**Issue by zumbak04** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2#318]
**Mod version:**
ab62a06ac25e2a0ec855cc6589830afda9145e63

**Are you using any submods/mods? If so, which?**
Nope

**Please explain your issue in as much detail as possible:**
Unlocalized name.

**Upload screenshots of the problem localization:**
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46384992/114407796-d6353b80-9bb9-11eb-9732-5ce95246f408.png)

</details>

**Comment by alescofet** [comment]
sorry if it's too obvious but the problem here is that the name appears with the "_" instead of a space?

**Comment by zumbak04** [comment]
> sorry if it's too obvious but the problem here is that the name appears with the "_" instead of a space?

Not only. Lothar and Lothair are 2 versions of the same name, you can't have 2 of them at the same time.

**Comment by zumbak04** [comment]
Noticed more characters with the same issue.
```
Adalbert_Albert
Arnulf_Arnulf
```
