### ISSUE TITLE
Really Old Short-lived Races

### ISSUE THREAD

**Issue by zumbak04** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2#323]
**Your mod version is:**
b3d86c8b081c943a1cc37b2b760b4eea497149b4

**What expansions do you have installed?**
NL

**Are you using any submods/mods? If so, which?**
No

**Please explain your issue in as much detail as possible:**
Looks like either character templates or character selectors spawn characters with really old age. I see they all are priests.

**Steps to reproduce the issue:**
Open the Character Selector.

**Upload an attachment below: .zip of your save, or screenshots:**
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46384992/114446579-71daa200-9be2-11eb-9ad9-804c7a7a373f.png)

</details>

**Comment by robmart** [comment]
They are not all priests, however they are all lowborn

**Comment by robmart** [comment]
Issue is not caused by any defines

**Comment by robmart** [comment]
Cause was missspelled trigger... of all things
