### ISSUE TITLE
SUCCESSION_EVENT_WINDOW_DEAD_OUTRO_WARCRAFT_MAGIC_GOOD never triggers

### ISSUE THREAD

**Issue by robmart** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2#328]
**Your mod version is:** 20068af

**What expansions do you have installed?** Northern Lords

**Are you using any submods/mods? If so, which?** None

**Please explain your issue in as much detail as possible:** SUCCESSION_EVENT_WINDOW_DEAD_OUTRO_WARCRAFT_MAGIC_GOOD is never used, even when you have the magic_good traits. Changing it to check for the traits individually doesn't work 
![bild](https://user-images.githubusercontent.com/4825809/114593817-d0f4f100-9c8c-11eb-9187-81a12e27e353.png)
Might effect other succession events.

**Steps to reproduce the issue:** Die when having the magic_good traits

**Upload an attachment below: .zip of your save, or screenshots:**
![bild](https://user-images.githubusercontent.com/4825809/114593734-b6bb1300-9c8c-11eb-96cc-475f5cabb6eb.png)

**Comment by MemeWizard** [comment]
Can't confirm
![image](https://user-images.githubusercontent.com/46576860/114595902-96dd1c80-9c97-11eb-9515-05c80316c499.png)
