### ISSUE TITLE
Not Existing Azshara River

### ISSUE THREAD

**Issue by zumbak04** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2#338]
**Describe your suggestion in full detail below:**
This river in Azshara doesn't exist. We have to fix it.
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46384992/115170631-1e7cbe00-a0d2-11eb-940e-596e368a8945.png)

</details>

**Comment by robmart** [comment]
Couldn't you close this issue and make it part of geographical inaccuracies issue instead? Feel like having all of those things in the same place is better.

**Comment by ValianBlue** [comment]
_Added to #342._
