### ISSUE TITLE
Undead shouldn't get ills

### ISSUE THREAD

**Issue by hamjustine** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2#341]
**Describe your suggestion in full detail below:**
I've seen that undead characters can contract illness like lover's pox. I don't think this can be possible as ... you know, they are dead. Maybe "rotten" at least.
![image](https://user-images.githubusercontent.com/25368000/115441437-24c58400-a211-11eb-91d2-4069766e6a66.png)

**Comment by zumbak04** [comment]
Important task indeed.

**Comment by SFP-NMOK** [comment]
The connected "Immortal Beings Should Not Get Illnesses" has been marked as complete so this should be completed also.
