### ISSUE TITLE
Сartography Inaccuracies

### ISSUE THREAD

**Issue by zumbak04** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2#342]
**Describe your suggestion in full detail below:**
So it's time to list all inaccuracies that should be fixed.

- [x] This mountain range. If it's inspired by WoW, its position isn't right.
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46384992/115467917-535c5280-a243-11eb-864f-da36168beb4e.png)
![image](https://user-images.githubusercontent.com/46384992/115468080-96b6c100-a243-11eb-8e24-b8a2248b64e5.png)

</details>

- [x] No trees in Eastern Lordaeron and Quel'thalas.
- [x] Gilneas county has a weird texture.
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46384992/115468341-0167fc80-a244-11eb-9e7d-bb2b5946883b.png)

</details>

- [x] Not existing mountain range in Azshara.
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46384992/115468427-2197bb80-a244-11eb-94d5-2291f0c78455.png)

</details>

- [x] No trees in Ashenvale.
- [x] No trees in Hyjal.
- [x] No trees in Northrend.

**Comment by zumbak04** [comment]
- [ ] These 2 rivers shouldn't be a thing. They're too small so they should take place on `rivers.bmp`.
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46384992/115624545-dba62a80-a30b-11eb-8ec2-371a742ef57f.png)

</details>

**Comment by zumbak04** [comment]
- [ ] More trees here, it's a forest
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46384992/115799384-745ea800-a3e9-11eb-8d44-663a5b52b77a.png)

</details>

- [ ] Less trees here, it's plains
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46384992/115799424-87717800-a3e9-11eb-925e-297625a2b252.png)

</details>

**Comment by ValianBlue** [comment]
**Describe your suggestion in full detail below:**
- [ ] This river in Azshara doesn't exist. We have to fix it. 
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46384992/115170631-1e7cbe00-a0d2-11eb-940e-596e368a8945.png)

</details>

**Comment by ValianBlue** [comment]
_This area of **Darkshore**, the counties of **Nandal** and **Lor'danel,** would benefit from a detail upgrade. Additionally, the **Cliffspring River** is missing._

- [ ] Darkshore Details Upgrade
- [ ] Add Cliffspring River

<details>
<summary>Current Political Map</summary>

![](https://i.imgur.com/f4hPuyy.png)
</details>

<details>
<summary>Current Terrain Map</summary>

![](https://i.imgur.com/lpVg2tE.png)
</details>

<details>
<summary>WoW In-Game Map</summary>

![](https://wow.gamepressure.com/gfx/ingamemaps/27.jpg)
</details>

<details>
<summary>WoW In-Game Terrain</summary>

![](https://i.imgur.com/D47watc.png)
</details>

**Comment by ValianBlue** [comment]
## Border Discrepancies off the coast of Durotar
<details>
<summary></summary>

![image](https://user-images.githubusercontent.com/40177753/229951775-4b8fd2af-3537-46e7-a72c-0aac1665ae44.png)
</details>

- [ ] South coastline of Durotar
- [ ] Isle of Fray
<hr>

## Floating Lines over Kalimdor
<details>
<summary></summary>

![image](https://i.imgur.com/Y4WNYAo.jpg)
</details>

- [ ] Remove Floating Lines
<hr>

## Ton'croa Misplaced Map Objects
<details>
<summary></summary>

![image](https://user-images.githubusercontent.com/40177753/229952567-217d653b-52f8-4f64-a590-9b98a055275d.png)
</details>

- [ ] Reassign Map Objects
<hr>

## Missing Trees
> Requested by @Gaben1025.
- [ ] Zandalar
- [ ] Pandaria
- [ ] "Most islands in the middle"
<hr>

**Comment by ValianBlue** [comment]
## Lordamere duchy building/capital wrong county
> In the duchy of Lordamere the capital of the duchy is Undernelly but the duchy building slot is on the Dawning Isles county.
<details><summary></summary>

![lordamereduchycapital](https://user-images.githubusercontent.com/86842532/233853004-8cccd485-504a-4027-9728-12df5a102d98.png)
</details>

- [ ] Reassign Duchy Building Slot

**Comment by ValianBlue** [comment]
# 5/11/23 Current Issues
## Darkshore
_This area of **Darkshore**, the counties of **Nandal** and **Lor'danel,** would benefit from a detail upgrade. Additionally, the **Cliffspring River** is missing._

- [ ] Darkshore Details Upgrade
- [ ] Add Cliffspring River

<details>
<summary>Current Political Map</summary>

![](https://i.imgur.com/f4hPuyy.png)
</details>

<details>
<summary>Current Terrain Map</summary>

![](https://i.imgur.com/lpVg2tE.png)
</details>

<details>
<summary>WoW In-Game Map</summary>

![](https://wow.gamepressure.com/gfx/ingamemaps/27.jpg)
</details>

<details>
<summary>WoW In-Game Terrain</summary>

![](https://i.imgur.com/D47watc.png)
</details>

## Gilneas
- [ ] Blackwald has rock texture.
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46384992/115468368-0dec5500-a244-11eb-9d94-0042d9cbc641.png)
</details>

## Northrend
- [ ] Northrend has weird textures in many places. Like rock texture here.
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46384992/115468679-7affea80-a244-11eb-8ed9-4a9822fb226c.png)
</details>

## Pandaria
- [ ] Not enough jungle trees in Krasarang.
- [ ] More trees here, it's a forest
<details><summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46384992/115799384-745ea800-a3e9-11eb-8d44-663a5b52b77a.png)
</details>

- [ ] Less trees here, it's plains
<details><summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46384992/115799424-87717800-a3e9-11eb-925e-297625a2b252.png)
</details>

## Uldum
- [ ] These 2 rivers shouldn't be a thing. They're too small so they should take place on `rivers.bmp`.
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46384992/115624545-dba62a80-a30b-11eb-8ec2-371a742ef57f.png)

</details>

## Missing Trees
> Requested by @Gaben1025.
- [ ] Zandalar
- [ ] Pandaria
- [ ] "Most islands in the middle"
<hr>
