### ISSUE TITLE
Improving MaAs with innovations

### ISSUE THREAD

**Issue by arithon** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2#349]
**Suggestion:**
- How about adding something like animal war training from wc3, giving bonus toughness to cavalry and aerial units?
- How about adding an innovation like storm hammers for cultures with gryphon riders to give them additional damage/counter vs heavy infantry/giants?

Zumbak suggested using "innovation_advanced_bowmaking" as vanilla example innovation.

**Comment by Gaben1025** [comment]
Who would get animal war training? Our would it be a tech for everyone?

Will storm hammers replace our further buff the next maas stats?

**Comment by arithon** [comment]
The idea with the storm hammers was to improve your existing and future gryphon riders MaA.

As for the animal training, I guess everyone could be able to research it, once they had aerial or cavalry MaA available.

**Comment by arithon** [comment]
Idea for the description of the Storm Hammer innovation:
The craftsmen of the Aeries, masters of their art, imbue the war hammers of their gryphon riders with the power of thunder and lightning, to strike true at their enemies and return to thwir owners safe and sound.

**Comment by Gaben1025** [comment]
![image](https://user-images.githubusercontent.com/74790101/117090955-cc6da680-ad27-11eb-922a-6d7ec9e32e19.png)
I tried adding counters, but as the instructions show you can only add those stats listed.  I will post a PR shortly with these techs.
