### ISSUE TITLE
life_expectancy doesn't use age values

### ISSUE THREAD

**Issue by robmart** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2#363]
**Your mod version is:** 
97e89fe

**What expansions do you have installed?** 
Nothern Lords

**Are you using any submods/mods? If so, which?**

**Please explain your issue in as much detail as possible:**
~~These should use the values, like the second one in the list does.~~ Can't use global values in modifiers. Workaround probably needed, otherwise perks/traits/modifiers that extend lifespan are useless to longer lived races.
![bild](https://user-images.githubusercontent.com/4825809/117042310-18125700-ad0c-11eb-9717-3df33680eb12.png)

**Comment by zumbak04** [comment]
It's a bug?

**Comment by zumbak04** [comment]
And does it really works?

**Comment by MemeWizard** [comment]
As far as I know, you can't use scripted values as modifier values

**Comment by MemeWizard** [comment]
> As far as I know, you can't use scripted values as modifier values

I mean, with calculations that uses non-local values.
So,
 `value = x` works
 `value = [local1 + local2]` works
`value = { if elf add 1, else if orc add 2, etc}` doesn't work

**Comment by robmart** [comment]
I mean if it doesn't use the values that means that the perks/traits/modifiers are completely irrelavent to longer lived races

**Comment by zumbak04** [comment]
> I mean if it doesn't use the values that means that the perks/traits/modifiers are completely irrelavent to longer lived races

They are irrelevant in any form because even the shortest among long-living races live up to 400. That's enough to change only 1-0 characters during the gameplay.

But if we are talking about the balance of giving life expectancy, it's definitely more fair to give them the same amouth of years without any multiplications.

**Comment by zumbak04** [comment]
@robmart close it then since its impossible.
