### ISSUE TITLE
Adapt character relationships

### ISSUE THREAD

**Issue by zumbak04** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2#4]
**Describe your suggestion in full detail below:**
- [x] `c_<Character ID>` doesn't work and need adaptation.
- [x] `add_friend = <Character ID>` to `set_relation_friend = character:<Character ID>`. No longer has to be in `effect` but works with it as well.
- [x] `add_lover = <Character ID>` to `set_relation_lover = character:<Character ID>`. No longer has to be in `effect` but works with it as well.
- [x] `add_rival = <Character ID>` to `set_relation_rival = character:<Character ID>`. No longer has to be in `effect` but works with it as well.
- [x] `add_spouse = <Character ID>` still works w/o `effect`.
- [x] Adapt `add_consort`.

**Comment by Malicos** [comment]
Mostly done. Please verify if there are issues.

**Comment by zumbak04** [comment]
Adapt `add_consort`.
