### ISSUE TITLE
Wildhammer "Brothers"

### ISSUE THREAD

**Issue by NovelConcept** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2#403]
**Describe your suggestion in full detail below:**
Canonically, Kurdran and Falstad are not brothers, just good friends. Falstad uses the clan name as his surname and was chosen to lead the Wildhammer clan after Kurdran went missing, but he's not actually related to him.

**Comment by elcascavel** [comment]
Kurdran and Falstad are no longer brothers, I removed that relationship in b86457b80fcd95db56a9f3d60ad48716c4f76e48.

However, this no longer guarantees that Falstad succeeds Kurdran which is apparently what's intended.
