### ISSUE TITLE
Troll Flags

### ISSUE THREAD

**Issue by zumbak04** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2#436]
**Describe your suggestion in full detail below:**
We need CoAs for these trolls titles:
- [x] e_drakkari
- [x] k_zuldrak
- [x] k_draktharon
- [x] k_frostmane
- [x] e_gurubashi
- [x] k_gurubashi
- [x] e_zandalari
- [x] k_zandalar
- [x] k_south_islands (Darkspear Islands and more)
- [x] e_zulfarrak
- [x] k_zulfarrak
- [x] e_amani
- [x] k_hinterlands

**Comment by kaldrskegg** [comment]
![drakkari_coa_concept](https://user-images.githubusercontent.com/46745564/121972402-49eef280-cd7b-11eb-9fcc-a943047917be.png)
underway
