### ISSUE TITLE
Kul Tiran CoAs

### ISSUE THREAD

**Issue by zumbak04** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2#437]
**Describe your suggestion in full detail below:**
So each Kul Tiran house has its own heraldry so it's important to add it:
- [ ] Stormsong dynasty and `d_stormsong` title
- [ ] Ashvane dynasty and `d_ashvane` title
- [ ] Waycrest dynasty and `d_drustwar` title

**Comment by Rekutur** [comment]
On it
