### ISSUE TITLE
Troll Religion Renames

### ISSUE THREAD

**Issue by kaldrskegg** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2#448]
**Describe your suggestion in full detail below:**
change troll religion names to Atal'Farrak, Atal'Aman, Atal'Drakkar, meaning "devoted Farrak/Aman/Drakkar" implying "devoted to loa of those people (farraki/amani/drakkari)", just because it is a bit shorter and sounds better than "Farrak'atali" and fits with the religious faction of Atal'ai (devoted ones)

**Comment by zumbak04** [comment]
> change troll religion names to Atal'Farrak, Atal'Aman, Atal'Drakkar, meaning "devoted Farrak/Aman/Drakkar"

It doesn't mean devoted people. Atal'<Something> is a name of a place, usually a temple.

**Comment by zumbak04** [comment]
Troll plural nouns end on `i`: Hakkari.

**Comment by zumbak04** [comment]
>  sounds better than "Farrak'atali"

We use Far'atali, not Farrak'atali.

**Comment by zumbak04** [comment]
> just because it is a bit shorter

It's not shorter: 
Atal'Farrak - 11 letters
Far'atali - 9 letters.

**Comment by MemeWizard** [comment]
> It doesn't mean devoted in terms of people.

<https://wowpedia.fandom.com/wiki/Zandali>

> Atal'ai = Devoted Ones.

From RPG, if that counts:

> Atal'Hakkar = "Devoted to Hakkar" or "In Honor of Hakkar".

**Comment by zumbak04** [comment]
> Atal'Hakkar = "Devoted to Hakkar" or "In Honor of Hakkar".

That's the name of the temple!

**Comment by zumbak04** [comment]
Atal'Gral, Atal'Hakkar, Atal'Dazar.

**Comment by zumbak04** [comment]
And we already had this conversation.
https://discord.com/channels/317351018050355200/751109648869752954/759075982212333578

**Comment by zumbak04** [comment]
We already had this conversation and everyone agreed on the current names.

**Comment by MemeWizard** [comment]
> That's the name of the temple!

> It doesn't mean devoted in terms of people.

Atal'ai, Atal'alarion, Atal'zul

<https://wowpedia.fandom.com/wiki/Atal%27ai_tribe>
<https://wowpedia.fandom.com/wiki/Atal%27alarion>
<https://wowpedia.fandom.com/wiki/Atal%27zul>

**Comment by MemeWizard** [comment]
> And we already had this conversation.

No, we had conversation about troll religion names, not about what `Atal'` means

**Comment by MemeWizard** [comment]
Whatever
