### ISSUE TITLE
Hellscream DNAs

### ISSUE THREAD

**Issue by zumbak04** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2#449]
**Describe your suggestion in full detail below:**
I need DNAs of both Hellscreams:
- [x] Grommash
- [x] Garrosh

When you make them post DNA here and ping me, @zumbak04, I'll add them in-game.

**Comment by hamjustine** [comment]
Garrosh DNA : 
![image](https://user-images.githubusercontent.com/25368000/123797170-33ea4180-d8e6-11eb-94de-d3aa2e86209b.png)
ruler_designer_2019635603={
	type=male
	id=0
	genes={ 		hair_color={ 44 255 44 255 }
 		skin_color={ 24 228 47 213 }
 		eye_color={ 47 136 52 167 }
 		gene_chin_forward={ "chin_forward_neg" 171 "chin_forward_neg" 122 }
 		gene_chin_height={ "chin_height_neg" 149 "chin_height_neg" 222 }
 		gene_chin_width={ "chin_width_neg" 255 "chin_width_neg" 198 }
 		gene_eye_angle={ "eye_angle_neg" 173 "eye_angle_neg" 134 }
 		gene_eye_depth={ "eye_depth_neg" 130 "eye_depth_neg" 142 }
 		gene_eye_height={ "eye_height_neg" 59 "eye_height_neg" 75 }
 		gene_eye_distance={ "eye_distance_neg" 98 "eye_distance_neg" 127 }
 		gene_eye_shut={ "eye_shut_neg" 157 "eye_shut_neg" 131 }
 		gene_forehead_angle={ "forehead_angle_pos" 135 "forehead_angle_pos" 57 }
 		gene_forehead_brow_height={ "forehead_brow_height_pos" 98 "forehead_brow_height_pos" 126 }
 		gene_forehead_roundness={ "forehead_roundness_pos" 232 "forehead_roundness_pos" 224 }
 		gene_forehead_width={ "forehead_width_pos" 204 "forehead_width_pos" 108 }
 		gene_forehead_height={ "forehead_height_pos" 145 "forehead_height_pos" 145 }
 		gene_head_height={ "head_height_pos" 175 "head_height_pos" 166 }
 		gene_head_width={ "head_width_pos" 88 "head_width_pos" 157 }
 		gene_head_profile={ "head_profile_neg" 160 "head_profile_neg" 156 }
 		gene_head_top_height={ "head_top_height_neg" 0 "head_top_height_neg" 68 }
 		gene_head_top_width={ "head_top_width_neg" 91 "head_top_width_neg" 42 }
 		gene_jaw_angle={ "jaw_angle_pos" 197 "jaw_angle_pos" 147 }
 		gene_jaw_forward={ "jaw_forward_neg" 189 "jaw_forward_neg" 249 }
 		gene_jaw_height={ "jaw_height_neg" 174 "jaw_height_neg" 245 }
 		gene_jaw_width={ "jaw_width_pos" 251 "jaw_width_pos" 191 }
 		gene_mouth_corner_depth={ "mouth_corner_depth_neg" 141 "mouth_corner_depth_neg" 127 }
 		gene_mouth_corner_height={ "mouth_corner_height_pos" 107 "mouth_corner_height_pos" 128 }
 		gene_mouth_forward={ "mouth_forward_neg" 130 "mouth_forward_neg" 0 }
 		gene_mouth_height={ "mouth_height_neg" 24 "mouth_height_neg" 19 }
 		gene_mouth_width={ "mouth_width_pos" 255 "mouth_width_pos" 230 }
 		gene_mouth_upper_lip_size={ "mouth_upper_lip_size_neg" 173 "mouth_upper_lip_size_neg" 130 }
 		gene_mouth_lower_lip_size={ "mouth_lower_lip_size_neg" 239 "mouth_lower_lip_size_neg" 228 }
 		gene_mouth_open={ "mouth_open_pos" 0 "mouth_open_pos" 140 }
 		gene_neck_length={ "neck_length_pos" 87 "neck_length_pos" 143 }
 		gene_neck_width={ "neck_width_pos" 255 "neck_width_pos" 170 }
 		gene_bs_cheek_forward={ "cheek_forward_pos" 139 "cheek_forward_neg" 17 }
 		gene_bs_cheek_height={ "cheek_height_pos" 43 "cheek_height_neg" 35 }
 		gene_bs_cheek_width={ "cheek_width_pos" 13 "cheek_width_pos" 143 }
 		gene_bs_ear_angle={ "ear_angle_neg" 217 "ear_angle_pos" 85 }
 		gene_bs_ear_inner_shape={ "ear_inner_shape_pos" 45 "ear_inner_shape_pos" 45 }
 		gene_bs_ear_bend={ "ear_upper_bend_pos" 167 "ear_upper_bend_pos" 12 }
 		gene_bs_ear_outward={ "ear_outward_pos" 49 "ear_outward_pos" 77 }
 		gene_bs_ear_size={ "ear_size_pos" 153 "ear_size_pos" 83 }
 		gene_bs_eye_corner_depth={ "eye_corner_depth_pos" 7 "eye_corner_depth_neg" 148 }
 		gene_bs_eye_fold_shape={ "eye_fold_shape_pos" 255 "eye_fold_shape_neg" 197 }
 		gene_bs_eye_size={ "eye_size_neg" 175 "eye_size_neg" 3 }
 		gene_bs_eye_upper_lid_size={ "eye_upper_lid_size_pos" 255 "eye_upper_lid_size_pos" 68 }
 		gene_bs_forehead_brow_curve={ "forehead_brow_curve_neg" 255 "forehead_brow_curve_pos" 88 }
 		gene_bs_forehead_brow_forward={ "forehead_brow_forward_pos" 93 "forehead_brow_forward_pos" 237 }
 		gene_bs_forehead_brow_inner_height={ "forehead_brow_inner_height_neg" 161 "forehead_brow_inner_height_neg" 2 }
 		gene_bs_forehead_brow_outer_height={ "forehead_brow_outer_height_pos" 255 "forehead_brow_outer_height_pos" 143 }
 		gene_bs_forehead_brow_width={ "forehead_brow_width_pos" 21 "forehead_brow_width_pos" 199 }
 		gene_bs_jaw_def={ "jaw_def_pos" 105 "jaw_def_pos" 222 }
 		gene_bs_mouth_lower_lip_def={ "mouth_lower_lip_def_pos" 167 "mouth_lower_lip_def_pos" 155 }
 		gene_bs_mouth_lower_lip_full={ "mouth_lower_lip_full_pos" 255 "mouth_lower_lip_full_pos" 245 }
 		gene_bs_mouth_lower_lip_pad={ "mouth_lower_lip_pad_pos" 25 "mouth_lower_lip_pad_neg" 218 }
 		gene_bs_mouth_lower_lip_width={ "mouth_lower_lip_width_pos" 85 "mouth_lower_lip_width_pos" 64 }
 		gene_bs_mouth_philtrum_def={ "mouth_philtrum_def_pos" 0 "mouth_philtrum_def_pos" 30 }
 		gene_bs_mouth_philtrum_shape={ "mouth_philtrum_shape_neg" 255 "mouth_philtrum_shape_pos" 80 }
 		gene_bs_mouth_philtrum_width={ "mouth_philtrum_width_pos" 123 "mouth_philtrum_width_neg" 37 }
 		gene_bs_mouth_upper_lip_def={ "mouth_upper_lip_def_pos" 255 "mouth_upper_lip_def_pos" 90 }
 		gene_bs_mouth_upper_lip_full={ "mouth_upper_lip_full_neg" 255 "mouth_upper_lip_full_neg" 246 }
 		gene_bs_mouth_upper_lip_profile={ "mouth_upper_lip_profile_pos" 95 "mouth_upper_lip_profile_pos" 120 }
 		gene_bs_mouth_upper_lip_width={ "mouth_upper_lip_width_pos" 163 "mouth_upper_lip_width_pos" 163 }
 		gene_bs_nose_forward={ "nose_forward_pos" 113 "nose_forward_pos" 163 }
 		gene_bs_nose_height={ "nose_height_pos" 255 "nose_height_pos" 237 }
 		gene_bs_nose_length={ "nose_length_neg" 255 "nose_length_neg" 104 }
 		gene_bs_nose_nostril_height={ "nose_nostril_height_pos" 167 "nose_nostril_height_pos" 217 }
 		gene_bs_nose_nostril_width={ "nose_nostril_width_neg" 171 "nose_nostril_width_neg" 130 }
 		gene_bs_nose_profile={ "nose_profile_pos" 51 "nose_profile_pos" 16 }
 		gene_bs_nose_ridge_angle={ "nose_ridge_angle_neg" 1 "nose_ridge_angle_pos" 194 }
 		gene_bs_nose_ridge_width={ "nose_ridge_width_neg" 255 "nose_ridge_width_pos" 34 }
 		gene_bs_nose_size={ "nose_size_pos" 255 "nose_size_pos" 242 }
 		gene_bs_nose_tip_angle={ "nose_tip_angle_pos" 93 "nose_tip_angle_pos" 149 }
 		gene_bs_nose_tip_forward={ "nose_tip_forward_neg" 255 "nose_tip_forward_neg" 130 }
 		gene_bs_nose_tip_width={ "nose_tip_width_neg" 39 "nose_tip_width_neg" 74 }
 		face_detail_cheek_def={ "cheek_def_02" 255 "cheek_def_02" 246 }
 		face_detail_cheek_fat={ "cheek_fat_01_neg" 255 "cheek_fat_04_pos" 72 }
 		face_detail_chin_cleft={ "chin_cleft" 255 "chin_cleft" 236 }
 		face_detail_chin_def={ "chin_def" 0 "chin_def" 249 }
 		face_detail_eye_lower_lid_def={ "eye_lower_lid_def" 255 "eye_lower_lid_def" 160 }
 		face_detail_eye_socket={ "eye_socket_03" 255 "eye_socket_03" 128 }
 		face_detail_nasolabial={ "nasolabial_01" 66 "nasolabial_04" 216 }
 		face_detail_nose_ridge_def={ "nose_ridge_def_neg" 68 "nose_ridge_def_neg" 44 }
 		face_detail_nose_tip_def={ "nose_tip_def" 103 "nose_tip_def" 126 }
 		face_detail_temple_def={ "temple_def" 146 "temple_def" 121 }
 		expression_brow_wrinkles={ "brow_wrinkles_04" 247 "brow_wrinkles_04" 247 }
 		expression_eye_wrinkles={ "eye_wrinkles_01" 250 "eye_wrinkles_02" 250 }
 		expression_forehead_wrinkles={ "forehead_wrinkles_01" 195 "forehead_wrinkles_01" 59 }
 		expression_other={ "cheek_wrinkles_right_01" 255 "cheek_wrinkles_both_01" 226 }
 		complexion={ "complexion_1" 255 "complexion_7" 154 }
 		gene_height={ "normal_height" 147 "normal_height" 147 }
 		gene_bs_body_type={ "body_fat_head_fat_medium" 153 "body_fat_head_fat_low" 169 }
 		gene_bs_body_shape={ "body_shape_average_clothed" 255 "body_shape_triangle_half" 233 }
 		gene_bs_bust={ "bust_clothes" 129 "bust_default" 129 }
 		gene_age={ "old_4" 131 "old_4" 15 }
 		gene_eyebrows_shape={ "no_eyebrows" 0 "no_eyebrows" 98 }
 		gene_eyebrows_fullness={ "no_eyebrows" 0 "no_eyebrows" 188 }
 		gene_body_hair={ "body_hair_dense" 255 "body_hair_sparse" 66 }
 		gene_hair_type={ "hair_wavy" 152 "hair_wavy" 152 }
 		gene_baldness={ "no_baldness" 127 "no_baldness" 127 }
 		eye_accessory={ "normal_eyes" 42 "normal_eyes" 42 }
 		teeth_accessory={ "normal_teeth" 0 "normal_teeth" 0 }
 		eyelashes_accessory={ "normal_eyelashes" 26 "normal_eyelashes" 26 }
 		gene_bs_ear_lenght={ "erect_ear_lenght" 20 "erect_ear_lenght" 37 }
 		special_eyebrows={ "no_eyebrows" 76 "no_eyebrows" 76 }
 		special_eyes={ "no_special_eyes" 255 "no_special_eyes" 0 }
 		gene_bs_mouth_tusks={ "mouth_fangs" 255 "mouth_fangs" 255 }
 		static_tusks={ "no_static_tusks" 255 "no_static_tusks" 0 }
 		gene_bs_ear_tip={ "ear_tip_pos" 226 "ear_tip_pos" 0 }
 		gene_bs_fingers={ "fingers_troll" 0 "fingers_troll" 0 }
 		gene_skin_value={ "skin_value_pos" 53 "skin_value_neg" 0 }
 		gene_race={ "creature_orc" 149 "creature_orc" 149 }
 		static_tusks={ "orcish_tusks" 127 "no_static_tusks" 0 }
 		hairstyles={ "no_hairstyles" 0 "all_hairstyles" 0 }
 		beards={ "no_beard" 255 "no_beard" 0 }
 		clothes={ "western_bedchamber" 95 "most_clothes" 0 }
 }
	override={
		portrait_modifier_overrides={
			custom_static_tusks=male_orcish_tusks_0
			custom_hair=no_hair
			custom_beards=male_empty
		}
	}

	entity={ 0 0 }
}
