### ISSUE TITLE
gurubashi kingdom title

### ISSUE THREAD

**Issue by kaldrskegg** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2#451]
change k_gurubashi to k_zulgurub and e_zulfarrak to e_farraki
all empire titles are then: gurubashi, farraki, drakkari, amani, zandalari
all kingdom titles are then: zulfarrak, zulgurub, zuldrak, zulaman, (except zandalar which is always called zandalar in lore)

**Comment by zumbak04** [comment]
> change k_gurubashi to k_zulgurub and e_zulfarrak to e_farraki

Note: you don't have AND YOU BETTER DON'T change the names. You should change just localization.
