### ISSUE TITLE
3 Dark Governments

### ISSUE THREAD

**Issue by zumbak04** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2#462]
**Describe your suggestion in full detail below:**
First, I want to allow these governments not only for the Scourge, Legion, Black Empire but for all demons, undead and void beings. So the Forsaken will be Necro Government:
# Requirements:
- Necro Government:
  - Ruler must be an undead
  - Necromancy must be allowed
- Demonic Government:
  - Ruler must be a demon
  - Fel must be allowed
- Eldritch Government:
  - Ruler must be a void being
  - Shadow must be allowed

# Effects:
- [x] Common: (in #463)
  - [x] No vassal contracts.
  - [x] Only rulers of the same religious family can inherit.
  - [x] Dark Frenzy instead of Crown Authority:
    - [x] Low Frenzy makes you weaker, strong Frenzy gives you strong modifiers.
    - [x] Frenzy decays over time so to be efficient they should do their mechanics.
- Necro Government: (in #463)
  - [x] Get Frenzy on converting provinces to their culture and religion (add cooldown on the province to avoid player abuse).
  - [x] Get Frenzy on winning armies and sieging.
  - [x] Killed knights become yours as undead. High Frenzy increases the chance.
  - High Frenzy gives these bonuses:
    - [x] Levy size
    - [x] Levy reinforce rate
    - [x] Army gold cost
- [x] Demonic Government:
  - [x] Get Frenzy on execution and torture.
  - [x] May summon demon knights instead of normal ones. High Frenzy increases the chance.
  - [x] Other demons visit court often. High Frenzy increases the chance.
  - High Frenzy gives these bonuses:
    - [x] Tyranny gain
    - [x] Movement speed
    - [x] Dread decay
- [x] Eldritch Government:
  - [x] Get Frenzy on execution and mind break.
  - [x] Attract other void beings. High Frenzy increases the chance.

# Interface:
Frenzy must be on the HUD, somewhere near Dread maybe or instead of Crown Authority.

**Comment by MemeWizard** [comment]
> High Frenzy relieves your stress.

> Get Frenzy by having high stress and being lunatic.

> Winning armies, sieging increase your stress.

That's a lot of negative synergy not only inside the concept itself, but with the game stress mechanic too.

The more stress you get, the more stress you lose?

Accumulating a lot of stress through warfare to get level 3 mental breakdown in order to acquire lunatic trait to get less stress seems mandatory.

> Don't have normal stress-relieving activities.

Which ones? Feasts and hunting? Well, maybe.
Petting your cat and dog? What about Mr. Bigglesworth?
Writing a journal? Twilight's Hammer writes down a lot of stuff.

> Chthonic

AFAIK, they are not directly related to underworld. Eldritch would be a better name.

**Comment by zumbak04** [comment]
> The more stress you get, the more stress you lose?

Yes, to force you to get more stress to keep bonuses.

> Petting your cat and dog? What about Mr. Bigglesworth?

Hmm... maybe we keep it.

> Writing a journal? Twilight's Hammer writes down a lot of stuff.

I need to investigate the loc to decide.

> AFAIK, they are not directly related to underworld. Eldritch would be a better name.

Yep, sounds better.

**Comment by ElMariuso** [comment]
Could the autorithy crown be replaced by mind control over necro governments?
There was this for the Lich King on CK2 but I don't think it is incoherent for any character who has this type of government.

**Comment by arithon** [comment]
> Killed knights become yours as undead. High Frenzy increases the chance.
Is this even possible? IIRC in ck2 you wanted to avoid reviving people at all cost. However, I like this concept. And if it works, I'd love to see priests/paladins to have a chance to revive your own fallen knights after battle.

**Comment by robmart** [comment]
> 
> 
> > Killed knights become yours as undead. High Frenzy increases the chance.
> 
> Is this even possible? IIRC in ck2 you wanted to avoid reviving people at all cost. However, I like this concept. And if it works, I'd love to see priests/paladins to have a chance to revive your own fallen knights after battle.

It is, we don't have to revive them. We can replace the kill effect with another effect.

**Comment by zumbak04** [comment]
> Could the autorithy crown be replaced by mind control over necro governments?

That's what I'm doing.
