### ISSUE TITLE
Marrying a human strips human's default clothes off.

### ISSUE THREAD

**Issue by riandaniar** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2#467]
**Your mod version is:**
orc-ethnicity-update #429 
**What expansions do you have installed?**
All.
**Are you using any submods/mods? If so, which?**
No.
**Please explain your issue in as much detail as possible:**
Marring a human as an orc strips the human's clothes off. 
**Steps to reproduce the issue:**
Start game as orc leader. Console command marry human or do so through gameplay. Human's default clothes are gone.
**Upload an attachment below: .zip of your save, or screenshots:**
<details>
  <summary>NSFW</summary>

![image](https://user-images.githubusercontent.com/46826667/122643870-8ec7b000-d112-11eb-904d-34de4c88ac9f.png)
</details>

**Comment by zumbak04** [comment]
Can't spot it on the current version so I supposed it's fixed somehow.
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46384992/134100280-de574377-6dd0-4111-9b6e-760405d9ca4a.png)

</details>
