### ISSUE TITLE
Change Vilebranch religion to Hakkar in Dark Portal start date

### ISSUE THREAD

**Issue by kaldrskegg** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2#483]
**Describe your suggestion in full detail below:**
Apparently the Vilebranch worshipped Hakkar until Cataclysm , so should change their religion to fit this.

![image](https://user-images.githubusercontent.com/46745564/123054450-28d67380-d405-11eb-8534-b4275b6c1350.png)
https://wowpedia.fandom.com/wiki/Vilebranch_tribe

**Comment by zumbak04** [comment]
For the Vilebranch to be well with Zul'jin they shouldn't be Hakkari in the 583.
