### ISSUE TITLE
Class adaptation

### ISSUE THREAD

**Issue by zumbak04** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2#5]
**Describe your suggestion in full detail below:**
If we want classes to be perk trees, it's time to add them.
`add_perk = <Name>` is syntax for adding perks. Must be in `effect`.

**Comment by zumbak04** [comment]
The class design doc is WIP and pinned in the dev chat.

**Comment by Raged50** [comment]
under review
