### ISSUE TITLE
Death CoAs

### ISSUE THREAD

**Issue by zumbak04** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2#549]
**Describe your suggestion in full detail below:**
Add a set of Coat of Arms for the Death religions (so it should be skulls, bones, and other undead stuff).

**Comment by zumbak04** [comment]
Some added in #556, but there may be more.

**Comment by Rekutur** [comment]
On it.

**Comment by Rekutur** [comment]
Solved for the foreseeable future.
