### ISSUE TITLE
Elemental faiths virtues and sins

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2#56]
**Describe your suggestion in full detail below:**

I suggest using this as reference

<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46576860/101166519-734ef900-3649-11eb-8679-e7b2faf99d25.png)

</details>

**Comment by riioze** [comment]
If I understood well we must change the vitues and sins so it matchs more with the elements ?

**Comment by zumbak04** [comment]
> If I understood well we must change the vitues and sins so it matchs more with the elements ?

Yep.
