### ISSUE TITLE
Adapt religions

### ISSUE THREAD

**Issue by zumbak04** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2#6]
**Describe your suggestion in full detail below:**
Adapt mod religions and cultures on #1.

### Notes:
Icons needed too.

Need to sort religions in new religious groups.
Every pagan religion in the vanilla has its own group. So the religius group now represents different confeissions/heresies of one faith.

If someone wants to do religions, please post a design document first for discussion.

### Tasks:
- Icons, https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2/pull/14
- [x] Split religions in religious groups
- Doctrines, https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2/pull/21
- Religious heads, https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2/pull/22
- Holy sites, https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2/pull/22

**Comment by Malicos** [comment]
Note: every religion as of uses a 16/09/20 uses placeholder hsv colors. All of them need to be replaced with their ck2 values or new values either in hsv or rgb.

**Comment by zumbak04** [comment]
Note: need to sort religions in new religious groups.
Every pagan religion in the vanilla has its own group. So the religius group now represents different confeissions/heresies of one faith.

**Comment by zumbak04** [comment]
Icons needed too.

**Comment by zumbak04** [comment]
Also, if someone wants to do religions, please post a design document first for discussion.

**Comment by zumbak04** [comment]
Updated tasks.

**Comment by zumbak04** [comment]
With the last PR finished, I would call it closed.
Though we may add more doctrines later.
