### ISSUE TITLE
G'huuni holy site

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2#60]
**Describe your suggestion in full detail below:**

Move G'huuni holy site from Heart of Y'Shaarj location to other place.

<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46576860/101240924-760e2480-3703-11eb-888b-8b7e6d48a573.png)

</details>

**Comment by zumbak04** [comment]
> Move G'huuni holy site from Heart of Y'Shaarj location to other place.

I wouldn't move to Zandalar because having all 5 holy places there is... OP.
