### ISSUE TITLE
Tirani (Tidemother) head of faith title does not behave as a Temporal Head of Faith title should

### ISSUE THREAD

**Issue by Laetoy** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2#608]
**Your mod version is:**
Copy Sha: 925a3922f4e592ec24bcb815e2223b594e7c239f
**What expansions do you have installed?**
Garments of the Holy Roman Empire, Fashion of the Abbasid Court, The Northern Lords
**Are you using any submods/mods? If so, which?**
None
**Please explain your issue in as much detail as possible:**
When you go to revoke the Head of Faith's titles, you cannot revoke all of them, and therefor you cannot destroy the head of faith title, and recreate it yourself.
**Steps to reproduce the issue:**
Try to revoke all of the Head of Faith's titles, aside from the head of faith title itself, this should destroy the head of faith title.
Their duchy title cannot be revoked as would be expected, thus they are stuck with 0 counties under their control, their duchy title, and the head of faith title.
For comparison try 1066 start Seljuks and revoke their own faith's caliph's duchy title, which destroys the head of faith title, and it can afterwards be recreated as normal.

**Comment by zumbak04** [comment]
It's due to the Tidesages title being landless. Temporal heads shouldn't be landless.
