### ISSUE TITLE
Make walls of Zul'gurub impassable 

### ISSUE THREAD

**Issue by Seoulbee** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2#615]
**Describe your suggestion in full detail below:**
Armies can currently freely move between the baronies of Van'keiki, outside of Zul'gurub to the south, and Gokuntea, inside of Zul'gurub. In game, there is a massive wall and a lot of mountains between these two provinces, with no possible way to get between on-foot. I think mountains should be added, and armies should be made unable to pass between.

**Comment by Remerod** [comment]
that seems like a great idea, hopefully we can get walls to, not just mountains as impassable.

**Comment by zumbak04** [comment]
Against our design.

**Comment by Seoulbee** [comment]
So the issue is that it'd make Zul'gurub too big? It could be added on top of Gokuntea as well. I just think there should be a Southern wall somewhere to block off that entrance to the city somewhere. Similar to the current Twilight Grove, where there's a single chokepoint entrance. Minus the mountains and shrinking the city, Zul'gurub still has always been depicted with massive stone walls, and I think it's immersion breaking to have armies coming through where they'd be.

**Comment by zumbak04** [comment]
> So the issue is that it'd make Zul'gurub too big? It could be added on top of Gokuntea as well. I just think there should be a Southern wall somewhere to block off that entrance to the city. Similar to the current Twilight Grove, where there's a single chokepoint entrance. Even with changing the mountains and shrinking the city, Zul'gurub has always been depicted with massive stone walls, and I think it's immersion breaking to have armies coming through where they'd be.

There's a story about the orcs invading the Gurubashi from the Dark Portal so in the lore there are no walls.
These walls should be seen just as a WoW design to divide leveling and raid locations.
https://wowpedia.fandom.com/wiki/Bleeding_Hollow_clan#The_First_War

**Comment by ValianBlue** [comment]
_While this is possible to implement in-game using the map editor. I believe the walls would be better and more accurately portrayed through an in-game building. Potentially a custom 3D model could be attached to this building._

_You are free to re-open this issue if you deem it fit to do so._
