### ISSUE TITLE
Add Mug'thol as a vassal of Sylvanas

### ISSUE THREAD

**Issue by Grekopithikos** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2#649]
**Describe your suggestion in full detail below:**
Mug'thol is an Ogre Lord who was one of the mobs that could've gotten under control by Sylvanas in a sidequest in the Dark Lady mission just like Blackthorn.
https://wowpedia.fandom.com/wiki/The_Dark_Lady_(WC3_Undead)
Since Blackthorn is also depicted as a vassal I think it is also reasonable to make him a vassal too.
https://wowpedia.fandom.com/wiki/Mug%27thol

There was also a gnoll named Snarlmane that could be possesed in the same mission, though there was no sidequest for him.
https://wowpedia.fandom.com/wiki/Snarlmane

**Comment by Grekopithikos** [comment]
There's also the forest troll warlord Zul'rogg
https://wowpedia.fandom.com/wiki/Zul%27rogg

**Comment by zumbak04** [comment]
Mug'thol and Blackthorn are in-game.

**Comment by zumbak04** [comment]
Mug'thol isn't a vassal tho.

**Comment by Grekopithikos** [comment]
btw why not change Blackthorn's lunatic trait to possesed?
