### ISSUE TITLE
Nazen Religion changes

### ISSUE THREAD

**Issue by BurnedCrusader** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2#682]
**Describe your suggestion in full detail below:**
_This has been split off from a larger issue_
Checked out Nerubians one day and some things didn't seem right about their religion
- Move one Nazeni holy site from Nordrassil to Ulduar. I honestly didn't even get this one. Nerubians never did ANYTHING in Kalimdor or Nordrassil, they don't worship nature nor they're full-on magically power hungry. In that matter Nerubians did try to overtake Ulduar, so it will make way more sense than Nordrassil.
- Disallow bastards(doesn't make sense for them to have bastards, since adultery is accepted and they're technically still a swarm)
- Disallow marriage of priests(viziers didn't needed to reproduce until after War of the Spider)
- Clerical function recruitment(we can't add a new religious tenet(for now maybe) and viziers did fight(Warcraft 3, WoW), so it would only make sense)
- Make priests only male(only females in Nerubian society were queens and they don't seem like religious leaders to me).

**Comment by Remerod** [comment]
I feel should get a lore update if anything. I don't disagree with it, it is well written but it should definitely have more flavor.  
This is the current description of it; 
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/79544635/134273751-ad9a9533-488f-4c1e-b1ab-68c0c33a8fa3.png)

</details>

the wiki (wowpedia) containing faith information on Nerubians describe their belief as this;
>In ancient Azjol-Nerub, there were five or six schools of religious thought, and theological debates were common. Eventually, however, nerubians have come to a conclusion that worshiping creatures from beyond the world is insane, and, in the words of the seer Ul'Tomon, "makes as much sense as a fly caught in a web worshiping the spider who is about to devour him". To modern nerubians, even the concept of "worship" itself is alien.

>their society broke away and opposed the Old Gods that their people once served as aqir, specifically Yogg-Saron.[5] The split happened early enough in nerubian history, that by the time of Arthas Menethil's ascension to the Lich King, Anub'arak commented that he had believed them to be only legend. 

Clearly stating that their where 6 faith's prior, and that now religion is a foreign element. and that they know of the former religions. I do think the religion is well thought out, but i think the flavor should reflex overcoming the old faith, like "once we believed bla bla, but the philosopher/seer Ul'Tomon teached us"makes as much sense as a fly caught in a web worshiping the spider who is about to devour him" and this-and that, now the Nazeni something~

On the subject on the 6 prior faith, i belev we could possible add them as 6 old faiths, four focusing on each old god, one on all the gods and the 6th one void/old god arcane knowledge or something and it would be this sixth that breaks out and form the Nazen 7th faith. We would then have some religions that somehow can be resurrected by the nerubian remnants seeking old salvation.

 I agree with @BurnedCrusader point on *Make priests only male . It feels females are important in the void worshiping aqir-and evolved races, also females are the dominant spider gender (who for instance eats her children) so they don't particularly really love their offspring or anything, we could have that like females where the dominant gender who happily served the old gods in the past, sacrificing their children in masses to the old gods. Ul'Tomon and his new 7th faith rebel and come out victorious and builds a new society, one where female no longer are present in the religious beliefs to make sure that the old gods are not worshiped again and then millennia pass and only legends remain (and ruins & tablets witch tell of the old faiths witch might be some kind of event chain to open them up, this will also change society to female dominant again).

If what i've written seems logical then perhaps Nazen could be describbed as something like this?
**Nazen**
_Long ago Ul'Tomon freed us from the maddening vehemence from ancient horrors whom thrived on our blood, labour and enforced Zeal. Carving a new path for us, Ul'Tomon scribe upon the obelisk of Nazen a new philosophy, one that denounce all faith and worship of outside beings whom would corrupt us. The Nazeni philosophy preaches reunification of emotions, so one can devote the mind Hierachy/Realm/Kingdom/domain. The life of one individual is not important compared the greatness of society. Where the one can fall, get eaten and become forgotten, the strength, survival and grandness of the many/nest/hive is Eternal. Thus Nazeni should always be willing to sacrifice themselves for the greater cause._
 
 Thoughts?

**Comment by Loralius** [comment]
I agree with everything in the OP. These changes I can incorporate into #839 if there are no objections. 

There is certainly a need for a lore revamp for the Nazen religion. The existing religion description is quite vague and even the religious family itself (Death) is dubious for bookmarks before they are vassalised by the Lich King. I don't if creating 6 custom sub-religions is the wisest or most necessary approach since most of this would be custom lore that likely would not be experienced by most players. 

What if we went with two: one for their original faith and the other for after submission to the scourge? One of them could take the form of a heresy, although I am unsure if it's possible across 2 different religious families. The scourged version would necessarily remain in the death group, however the old religion might ironically best fit within _order_ -> _arcane_, albeit with many magic types accepted.
