### ISSUE TITLE
Nerubian MaAs and innovations

### ISSUE THREAD

**Issue by BurnedCrusader** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2#687]
**Describe your suggestion in full detail below:**
In lore Nerubians did tame some beasts and made underground architectural wonders, not only in buildings themselves, but traps also. I suggest adding the following things since if we're ever gonna see only surface Nerubians they're gonna need any buffs they can get, while also getting a bit of flavor.
- Add [Arachnathid](https://wowpedia.fandom.com/wiki/Arachnathid) as cultural beasts for Nerubians and any culture in Northrend willing to make them their own. In lore these beasts were guardians for Azjol'Nerub and few other places, but mostly still were wild beasts with poison on their side. I think they will make a good addition as "normal" beast MaA with medium stats and a little higher attack.
- Add [Obsidian destroyers](https://wowpedia.fandom.com/wiki/Obsidian_destroyer) for Nerubians and Qiraji, letting Scourge adapt them later. They we're added to Scourge in MaA PR, but not to Qiraji or even Nerubians. I mean, do I have to say more?
- Add [Jormungar](https://wowpedia.fandom.com/wiki/Jormungar) as MaA. I think we should split them into two types - siege beasts [Jormungar Tunnelers](https://wowpedia.fandom.com/wiki/Jormungar_Tunneler) and massive beasts Jormungar Wyrms. Basically younger Jormungar, as they're weaker, are used to dig under enemy fortifications and\or in them. As Jormungar reach wyrm stage of their life cycle they can now be used at proper battles without any large risks. As they're big and said to swallow a dwarf whole they should be good at attack and probably can easily run down enemies from down below, but they have medium defense(heavily wounded Muradin turning into Avatar almost made one's head fly off) and don't really have a way to cover retreating troops.
- Add Nerubian Architecture as innovation that allows building of new structures, like ziggurats, nerubian fortresses(based on necropolises) or even traps as defensive structure; shortens time and cost to build. Nerubians were very good at traps and even LK was amazed by their style and later adopted it. I suggest to add two different versions for original Nerubian architecture and adopted undead one, which has nerubian fortresses replaced with necropolises.

**Comment by Gaben1025** [comment]
> **Describe your suggestion in full detail below:** In lore Nerubians did tame some beasts and made underground architectural wonders, not only in buildings themselves, but traps also. I suggest adding the following things since if we're ever gonna see only surface Nerubians they're gonna need any buffs they can get, while also getting a bit of flavor.
> 
> * Add [Arachnathid](https://wowpedia.fandom.com/wiki/Arachnathid) as cultural beasts for Nerubians and any culture in Northrend willing to make them their own. In lore these beasts were guardians for Azjol'Nerub and few other places, but mostly still were wild beasts with poison on their side. I think they will make a good addition as "normal" beast MaA with medium stats and a little higher attack.
> * Add [Obsidian destroyers](https://wowpedia.fandom.com/wiki/Obsidian_destroyer) for Nerubians and Qiraji, letting Scourge adapt them later. They we're added to Scourge in MaA PR, but not to Qiraji or even Nerubians. I mean, do I have to say more?
> * Add [Jormungar](https://wowpedia.fandom.com/wiki/Jormungar) as MaA. I think we should split them into two types - siege beasts [Jormungar Tunnelers](https://wowpedia.fandom.com/wiki/Jormungar_Tunneler) and massive beasts Jormungar Wyrms. Basically younger Jormungar, as they're weaker, are used to dig under enemy fortifications and\or in them. As Jormungar reach wyrm stage of their life cycle they can now be used at proper battles without any large risks. As they're big and said to swallow a dwarf whole they should be good at attack and probably can easily run down enemies from down below, but they have medium defense(heavily wounded Muradin turning into Avatar almost made one's head fly off) and don't really have a way to cover retreating troops.

Will be added in #746
