### ISSUE TITLE
All Remove Child cap mod doesn’t work on non human character

### ISSUE THREAD

**Issue by Budy31** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2#697]
**Describe your suggestion in full detail below:**
All remove child cap mod on steam doesn’t work on non human character, would be nice if it’s work on all character.

**Comment by zumbak04** [comment]
Don't get what you mean.
Don't know this mod, don't know what it does.

**Comment by Budy31** [comment]
Example for the mod I'm using

https://steamcommunity.com/sharedfiles/filedetails/?id=2247668815
The problem is that this mod appear to doesn't work on non human ethnicities character (tried it on highborne & high elves wife & it still capped at 6).

**Comment by zumbak04** [comment]
> https://steamcommunity.com/sharedfiles/filedetails/?id=2247668815
> The problem is that this mod appear to doesn't work on non human ethnicities character (tried it on highborne & high elves wife & it still capped at 6).

It's intended, the changelog is here: https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2/pull/513
