### ISSUE TITLE
Adapt CoA Cultures

### ISSUE THREAD

**Issue by zumbak04** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2#710]
**Describe your suggestion in full detail below:**
We have to check every our culture and culture group and make sure it has fitting vanilla CoA culture. Like centaurs probably has to have Mongol or Turkish CoA graphical culture.
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46384992/134736269-dc06f8c7-8775-4e8f-ad8d-6665f2e09f9e.png)

</details>

**Comment by Loralius** [comment]
### Issue unlinked to keep it open until all cultures complete

- [ ] #851 includes updates for human group. ***Pending Review***
  - Hillsbrad, Theramore, and Kirin Tor added to `charge` and `hr_charges_list`.
  - Gilneas added to `pagan_single_charge_list`. 
    - Kul Tirans are already in this list, yet are descended from Gilneans with whom they share certain cultural similarities such as human/drust druidic wicker traditions and harvest witchcraft.
