### ISSUE TITLE
Hozen Rulers don't Spawn with creature_hozen trait

### ISSUE THREAD

**Issue by Fishmesch** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2#714]
**Your mod version is:**
Master Branch
**What expansions do you have installed?**
Northern Lords
**Are you using any submods/mods? If so, which?**
No
**Please explain your issue in as much detail as possible:**
Hozen rulers (and their generated family members) are spawning without a creature_hozen trait, essentially making them humans.
**Steps to reproduce the issue:**
Play game at any start date and open the ruler page for a ruler of a Hozen-culture provinces.
**Upload an attachment below: .zip of your save, or screenshots:**
<details>
<summary>Screenshots of trait-less Hozen rulers</summary>

![hozenmissing2](https://user-images.githubusercontent.com/91395661/134802639-0f733e9b-368a-4a7c-8fd9-67aa56bf587a.png)
![hozenmissing1](https://user-images.githubusercontent.com/91395661/134802510-ce19ae27-ab04-4cc2-bea0-e9e5491a01f5.png)
![hozenmissing3](https://user-images.githubusercontent.com/91395661/134802536-2af47f98-2046-4622-81ee-1ca9baab5f27.png)
</details>

**Comment by Fishmesch** [comment]
Wolvar and Gorlocs also seem to spawn without their race traits.

**Comment by zumbak04** [comment]
Can't confirm.
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46384992/134938707-9f4068b5-de7f-4665-89a0-23d76078263e.png)

</details>
