### ISSUE TITLE
Evil Governments cannot build or upgrade buildings

### ISSUE THREAD

**Issue by Laetoy** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2#715]
**Your mod version is:**
f536dafc4a6004de1fc5f4247595e39485859661
**What expansions do you have installed?**
Garments of the Holy Roman Empire, Fashion of the Abbasid Court, The Northern Lords
**Are you using any submods/mods? If so, which?**
none
**Please explain your issue in as much detail as possible:**
Evil Governments for Demons/Old god followers/undead cannot build or upgrade their buildings
**Steps to reproduce the issue:**
Pick a character with an evil government type and try to build something
**Upload an attachment below: .zip of your save, or screenshots:**
![image](https://user-images.githubusercontent.com/22545985/134803835-d76552c7-128c-4d0d-bb14-9aef9d7c6307.png)

**Comment by ercarp** [comment]
All three of these government types have a lot of potential for custom buildings, so I don't imagine this being the case forever. It may just be disabled for the time being as they don't have any custom buildings in the mod yet (as far as I know).

**Comment by zumbak04** [comment]
> It may just be disabled

Nah, it's a bug.
