### ISSUE TITLE
Exchange Gold/Prestige/Faith for bonuses 

### ISSUE THREAD

**Issue by Gaben1025** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2#721]
- Could we add desicions or a new tab where we allow the player to exchange their resources for other resources at 5:4 ratio with no cooldowns? Ex.
 - "Ask around for gold": -100 prestige +80 gold
 - "Commission Statue": -100 gold +80 prestige 
 - "Give a tithe": -100 gold +80 faith
 - And so on for those 3 resources, but I would also like to see bonuses like gold/prestige/faith investments can buy faster building speeds, fascination discovery, levy reinforcement, culture conversion etc.

Note: I'm aware that a feast has the same concept of gold for prestige, but it's not guaranteed and it's on a cooldown. I also know you can ask the pope for money, but that is also on a cooldown and hurts opinion which is slightly different from what I'm proposing.

**Comment by zumbak04** [comment]
It's already in the vanilla.

> * "Ask around for gold": -100 prestige +80 gold

Basically, it's this and this.

<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46384992/135267169-8b467613-e746-43fe-9f31-f7d7cb261b3a.png)

</details>

> * "Commission Statue": -100 gold +80 prestige

It's this.
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46384992/135267089-cf063e20-c3ff-4097-ab31-56469181d5b4.png)

</details>

> "Give a tithe": -100 gold +80 faith

It's this.
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46384992/135267089-cf063e20-c3ff-4097-ab31-56469181d5b4.png)

</details>

https://ck3.paradoxwikis.com/Lifestyle

**Comment by zumbak04** [comment]
> with no cooldowns?

And this sounds so bad for gameplay.
