### ISSUE TITLE
Amani faith magic doctrines

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2#726]
**Describe your suggestion in full detail below:**

> Arcane magic appears to be unpopular among forest trolls and Huntsman Markhor said they dislike how other races abuse arcane magic.

https://wowpedia.fandom.com/wiki/Forest_troll

**Comment by zumbak04** [comment]
Don't forget to add labels.
