### ISSUE TITLE
Buff or change effect of Early Modern Governance tech

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2#743]
**Describe your suggestion in full detail below:**

+2 vassal limit doesn't sounds attractive enough to research it for several decades

<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46576860/138170537-c9735462-a443-42d4-abe9-791f0d37cf75.png)

</details>

**Comment by MemeWizard** [comment]
Dunno, I wouldn't pick that either, but that's at least a bit better.

Dukes/kings/emperors have a 20/40/60 vassal limit by default.
And dukes and counts have a realm size limit of 30 counties, with each county over the limit giving an overextension penalty.

So, this tech is useless for your vassals - barons and counts because they don't have vassals (barons don't count for the vassal limit), and dukes because they can't have that much land without penalties.
And I have never really concerned myself with the vassal limit while playing as kings or emperors because their limit is already big enough for me.

How about +5 vassal limit + additional bonus, something like +5% vassal tax contribution?

**Comment by Gaben1025** [comment]
Ok I will put that into the spreadsheet and work out the balance
