### ISSUE TITLE
Introductory Events

### ISSUE THREAD

**Issue by Malicos** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2#75]
**Describe your suggestion in full detail below:**
Notable lore characters should receive flavor introductory events that describe their lore and potential ambitions (for example Blackhand, Terenas Menethil, Thoras Trollbane, etc.)

**Comment by MemeWizard** [comment]
Even if we ever add them, this event type should come with a game rule to disable it.

If I got you right, then I must say that, **in my opinion**, these events don't lead to anything, don't do anything, and therefore don't have any function or purpose other than just wasting player click and time.

> for example Blackhand

Also, whoever wants to write them must avoid firing this event at the same time as other global events. Bloating the player screen with multiple event windows wasn't cool in ck2 either.

**Comment by zumbak04** [comment]
Don't bookmark texts serve the same purpose?
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46384992/102990070-2ff0f780-4530-11eb-911a-abd9a579f1e2.png)

</details>

**Comment by Caitqua** [comment]
Agreed, and I wanted to do a little bit with the bookmarks as well. So we could probably just wrap those together.
