### ISSUE TITLE
errorspam from wc_being_events.txt and wc_genetic_traits.txt

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2#758]
**Your mod version is:**
363ea8978

**What expansions do you have installed?**
None

**Are you using any submods/mods? If so, which?**
2d graphical only

**Please explain your issue in as much detail as possible:**
These errors pop-up once every few days after starting the game

> [jomini_script_system.cpp:169]: Script system error!
  Error: has_graphical_culture trigger [ Wrong scope for trigger: character, expected culture ]
  Script location: file:  file:  file: common/traits/wc_genetic_traits.txt line: 242; dire_possible_trigger line: 2; is_race_no_gene_trigger line: 21

> [jomini_script_system.cpp:169]: Script system error!
  Error: add_opinion effect [ target character was null ]
  Script location: file: events/wc_events/wc_being_events.txt line: 211

> [jomini_script_system.cpp:169]: Script system error!
  Error: Event target link 'scope' returned an unset scope
  Script location: file: events/wc_events/wc_being_events.txt line: 211

> [jomini_script_system.cpp:169]: Script system error!
  Error: Undefined event target 'killer'
  Script location: file: events/wc_events/wc_being_events.txt line: 211

**Steps to reproduce the issue:**
Unpause the game

**Upload an attachment below: .zip of your save, or screenshots:**
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46576860/141059186-647ad9cc-fd76-41a3-9c4e-cc6443cf6994.png)

</details>

**Comment by zumbak04** [comment]
Fixed in https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2/pull/762/commits/82a3f9c42953107eb436fed23891826815695463.
