### ISSUE TITLE
Update Furbolg Model to Reforged

### ISSUE THREAD

**Issue by zumbak04** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2#78]
**Describe your suggestion in full detail below:**
So far, we use WotLK model for furbolgs and it has or quality. Reforged one looks much better. @TheGroxEmpire mentioned a possible way to export it:
https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2/pull/33#pullrequestreview-555565696

**Comment by kaldrskegg** [comment]
No longer in scope
