### ISSUE TITLE
Limit mercenaries for cultures with certain religions

### ISSUE THREAD

**Issue by Gaben1025** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2#780]
- Using religious doctrines we should limit mercenary companies for the cultures that have certain religions

**Comment by MemeWizard** [comment]
Excuse me, but how exactly do you plan to use **_religious_** doctrines to limit mercenary companies for the **_cultures_**?

**Comment by MemeWizard** [comment]
Never mind, I think I got it
You probably should tie it to `special_doctrine_end_justifies_means` then

**Comment by MemeWizard** [comment]
> I think I got it

(No, I still didn't)

**Comment by Gaben1025** [comment]
Not sure, @zumbak04 of how to implement, but we can use the mercenary_count_mult modifier
