### ISSUE TITLE
Dragonhawk Riders men at arms should counter aerial units as well as massive aerial

### ISSUE THREAD

**Issue by Laetoy** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2#792]
**Describe your suggestion in full detail below:**
Dragonhawk riders are an exceptional anti-air air unit in WC3. Currently in the mod they counter Massive Aerial, but not regular Aerial units. This feels a bit off.

That's all.

**Comment by Loralius** [comment]
Working changes at #838
