### ISSUE TITLE
Integration of Bloodline modules

### ISSUE THREAD

**Issue by Malicos** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2#82]
**Describe your suggestion in full detail below:**
We should ask for permission to use Artifact and Bloodline modules from CK3 Mod Coop and integrate them into our mod, then port associated CK2 content.

**Comment by arithon** [comment]
You definitely have my vote on this :)

**Comment by robmart** [comment]
Any chance for the [society module](https://steamcommunity.com/sharedfiles/filedetails/?id=2433006779)?

**Comment by zumbak04** [comment]
> Any chance for the [society module](https://steamcommunity.com/sharedfiles/filedetails/?id=2433006779)?

Any. Though Ivent tested them so cant tell for sure.

**Comment by zumbak04** [comment]
The artifact module isn't needed since they will appear in the vanilla with the next DLC.
