### ISSUE TITLE
Masonic Faith does not allow for bastard legitimization

### ISSUE THREAD

**Issue by Grekopithikos** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2#856]
**Your mod version is:**
don't remember
**What expansions do you have installed?**
Norhten Lords
**Are you using any submods/mods? If so, which?**
no
**Please explain your issue in as much detail as possible:**
The Masonic faith does not allow for bastard legitimization, even though all other light faiths do.
This is strange because I thought Masonry was one of the more liberal faiths that allowed for more things.
In fact I'd even go as far as to have them have the No Bastards doctrine.
**Steps to reproduce the issue:**
Check masonry faith
**Upload an attachment below: .zip of your save, or screenshots:**
![2022-01-22 (1)](https://user-images.githubusercontent.com/70974452/150640085-6d3f1232-f677-40dd-855b-c1fe2eb0a9e9.png)
![2022-01-22](https://user-images.githubusercontent.com/70974452/150640093-ca8cdbc5-b062-4cdb-b747-8eb912ea0282.png)

**Comment by Loralius** [comment]
> This is strange because I thought Masonry was one of the more liberal faiths that allowed for more things.

Can you provide a source for this?

**Comment by Grekopithikos** [comment]
> Can you provide a source for this?

Well I can't really provide a source for this as the faith itself only exists in this mod but they are supposed to represent the Defias' anti-authority ideology and it is also apparent if you take a look at their other doctrines you'll see that they aren't as strict as the mainline Light faith, not having any type of magic be criminal and being accepting of deviancy and witchcraft.

**Comment by Grekopithikos** [comment]
Looking at the files, it has doctrine_bastardry_all which is No Legitimization instead of doctrine_bastardry_none, which is the one that legitimizes all bastards.

I suspect that the original intention behind the change was to give the faith the "No Bastards" doctrine, but due to their confusing names in the code they got mixed up.


It doesn't make much sense otherwise to me at least. Why would the Masonics be stricter on that specific aspect than the Church of Holy Light?
