### ISSUE TITLE
Theologian Perk

### ISSUE THREAD

**Issue by Gaben1025** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2#864]
- Theologian perk should probably have three icons of Warcraft religions instead of Abrahamic and Buddhist icons

![image](https://user-images.githubusercontent.com/74790101/151681432-3c5777d8-e5fe-4cb3-9b21-73187fcaeb21.png)

**Comment by Grekopithikos** [comment]
The Holy Light icon should definitely be used
Maybe a totem too to represent shamanism?
Also the Islam icon could be edited to be Elunism
