### ISSUE TITLE
Mercenary Names

### ISSUE THREAD

**Issue by zumbak04** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2#87]
**Describe your suggestion in full detail below:**
Add mercenary names in `Warcraft-Guardians-of-Azeroth-2\common\culture\cultures` files.
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46384992/104107491-f6611000-52d5-11eb-849e-be777bfc7243.png)
![image](https://user-images.githubusercontent.com/46384992/104107510-1690cf00-52d6-11eb-9544-9111c77a1c73.png)

</details>

**Comment by ercarp** [comment]
Some examples of Mercenary Company names used in Vanilla CK3:

- `<blank>` Band
- Army of `<blank>`
- Riders of `<blank>`
- `<blank>` Companions
- Band of `<blank>`
- Company of `<blank>`
- `<blank>` Host
- Brothers of `<blank>`
- Followers of `<blank>`
- `<blank>` Company
- Guards of `<blank>`
- Guardians of `<blank>`
- Retinue of `<blank>`
- Host of `<blank>`
- Marchers `<blank>`
- Keepers of `<blank>`
- Raiders of `<blank>`
- Servants of `<blank>`
- `<blank>` Guard
- `<blank>` Gang
- `<blank>` Raiders
- `<blank>` Sellswords
- `<blank>` Fighters
- `<blank>` Blades
- Sons of `<blank>`
- `<blank>` Brotherhood
- `<blank>` Warriors

Some more unique examples:

- Slaughterers
- Redshanks
- Gallowglasses
- Count's Exiles
- Forest Wolves
- Union of Swords
- Desert Brethren

**Comment by zumbak04** [comment]
For reference, the vanilla localizations are in `Crusader Kings III\game\localization\english\mercenaries_l_english.ym`.

**Comment by zumbak04** [comment]
`[CULTURE.GetNameNoTooltip]` will get culture name.
`[TITLE.GetNameNoTierNoTooltip]` will get mercenaries base.
