### ISSUE TITLE
Holy Order Names

### ISSUE THREAD

**Issue by zumbak04** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2#88]
**Describe your suggestion in full detail below:**
Add holy order names in `Warcraft-Guardians-of-Azeroth-2\common\religion\religions` files.
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46384992/104107544-5f488800-52d6-11eb-9c65-5f22a3d5332d.png)

</details>

**Comment by zumbak04** [comment]
More info:
https://ck3.paradoxwikis.com/Localization is a basic localization article.
So the thing enclosed in `name = "<Name>` should refer to localization string somewhere in `Warcraft-Guardians-of-Azeroth-2\localization\english`. A new file can be added there.

**Comment by zumbak04** [comment]
A few lore names can be found here:
https://wow.gamepedia.com/Category:Paladin_organizations
https://wow.gamepedia.com/Category:Organizations_by_class
https://wow.gamepedia.com/Category:Organizations

**Comment by zumbak04** [comment]
> The `coat_of_arms` can stay the same.

Update: remove `coat_of_arms` and its argument. It's not needed.
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46384992/108262043-dac31200-717d-11eb-8e3b-7b3dcf9fbb30.png)

</details>

`the` at the beginning not needed.

**Comment by ercarp** [comment]
Some examples of Holy Order naming taken from Vanilla CK3:

- `<blank>`'s Chosen
- Knights of `<blank>`
- Brotherhood of `<blank>`
- Order of `<blank>`
- Warriors of `<blank>`
- `<blank>` Order
- Servants of `<blank>`
- Chosen of `<blank>`
- Sons of `<blank>`
- Guardians of `<blank>`
- Legion of `<blank>`
- `<blank>` Warriors
- `<blank>` Guardians

**Comment by zumbak04** [comment]
For reference, the vanilla localizations are in `Crusader Kings III\game\localization\english\holy_orders_l_english.yml`.

**Comment by zumbak04** [comment]
`[TITLE.GetNameNoTierNoTooltip]` will get holy order base.
`[FAITH.GetAdjectiveNoTooltip]` will get faith adjective.
`[FAITH.WarGodName]` will get the name of the war god.
`[FAITH.HighGodName]` will get the name of the high god.
