### ISSUE TITLE
Add Racial Traits Back

### ISSUE THREAD

**Issue by zumbak04** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2#9]
**Describe your suggestion in full detail below:**
Add racial traits back on #8.
Tasks:
- [x] Icons
- [ ] Effects

Update: we've added them but without effects. We've added a design document to balance them. It's pinned in the dev chat.

**Comment by zumbak04** [comment]
The progress is on `racial-stats`.

**Comment by Raged50** [comment]
added
