### ISSUE TITLE
Game crash on launch

### ISSUE THREAD

**Issue by Lurthemir** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2#932]
**What problem are you encountering during launching the mod?**

I installed the mod according to the instructions. I ensured that I copied the .mod file into both the \mod folder and kept it in the \Warcraft-Guardians-of-Azeroth-2 folder. On game launch, a Warcraft-themed loading screen appears and after about ten seconds of loading the game crashes to desktop.

**Comment by Statharas** [comment]
Are you running 1.4.4 and without Royal Court?

**Comment by Lurthemir** [comment]
That worked, Thank you.
