### ISSUE TITLE
"Questing" System

### ISSUE THREAD

**Issue by Seoulbee** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2#943]
**Describe your suggestion in full detail below:**
Decisions for all landed characters to put out "quests" in their counties/baronies. These quests would be related to modifiers on the baronies that represent mob problems. Small murloc tribes, fel corruption, gnoll or trogg incursions, etc. There could also be special schemes to create these problems in foreign baronies, or to rescue kidnapped characters from foreign prisons(Like the player characters did with Talanji to gain the favor of the Zandalari), or to involve adventurers in special murder schemes that are styled like WoW Dungeons. Adventurers could get special traits for being involved in said feats. There'd be a decision to put out a bounty on dealing with these domestic issues, and adventuring characters might take them up, and give you an event pop-up about them failing or succeeding. Said adventurers could then have other events related if you let them stay in your kingdom doing work for you. Sleeping with your daughter, drunkenly killing one of your knights in a brawl, etc, to add more flavor to it all.

**Comment by Gaben1025** [comment]
#92

**Comment by Seoulbee** [comment]
Oop my bad.
