### ISSUE TITLE
Big Portraits

### ISSUE THREAD

**Issue by zumbak04** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2#968]
**Please explain your issue in as much detail as possible:**
Portraits are too big. Need to fix it in `window_character.gui`. I would compare our file and vanilla one to find the issue.

**Steps to reproduce the issue:**
Look at any portrait.

**Upload an attachment below: .zip of your save, or screenshots:**
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46384992/202232182-668fe9cf-bf3b-4e90-913c-64a8b8285ab6.png)

</details>

**Comment by VespertinePetrichor** [comment]
Restored code to vanilla as a test, but it results in a CTD. The relevant lines of code are in the image. I took a look at the GUI wiki but there isn't enough there to help me make sense of what I'm looking at.

Error logs are showing gui issues in 3 files which are linked by the presence of 
`[Character.GetAge]` and `???` in `text = ` or `raw_text =`
- \gui\multiplayer_lobby.gui
- \gui\shared\lists.gui
- \gui\window_character.gui

![image](https://user-images.githubusercontent.com/77478662/204117274-906b1972-371c-4ed0-8509-b59f47099b3f.png)
