### ISSUE TITLE
Update court_scene.shader

### ISSUE THREAD

**Issue by zumbak04** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2#972]
**Please explain your issue in as much detail as possible:**
There are 2 shader files: `portrait.shader` and `court_scene.shader`. The first used for portraits, the second used for court location. Need to adapt `court_scene.shader` to `portrait.shader`: it should have all the effects `portrait.shader` has.

**Comment by Chomski2** [comment]
`court_scene.shader` have all the `portrait.shader` effects
