### ISSUE TITLE
Different game Design philosophy

### ISSUE THREAD

**Issue by edlani** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2#976]
_**The CK3 typical gameplay does not match Warcraft.**_

I think its not controversial to say a mod based on Game of Thrones can definitely work in CK3. Something like Elder Scrolls can also do this to a degree because the world building of Elder Scrolls allows it to have such depth but Warcraft lore is different.

I have seen the world map and the amazing amount of duchies, counties and size that it has... its too much! its too big! When the orcs were conquering Stormwind they weren't doing it country by county in such tiny portions. Its quality over quantity when it comes to warcraft, so the amount of zones should be smaller but much, much more significant.

Also what Warcraft writing thrives from is the amazing diversity between its races. The gameplay of Night Elves should be much more different than Gnomes. The Night Elves should not care which small portion of Ashenvale belongs to which Night Elf family but rather the responsibility of conducting the vigil in that area against threats of outside.
Gnomes? It should be about inventions, trade, technology and exploration. Meanwhile Humans should be more closer to what we have in CK3 with different noble families to see who can get to the top while the Orcs is the exact opposite, its a game to see who can stay at the top as warchief and how they can expand the size of their Horde with new alliances.

_**Turning the game format on its head.**_

In short the game should not be one about expanding your empire with different politics but to roleplay that race and those characters faithfully. Maybe Total War would be easier but I think CK3 can add nuances that Total War can't... but you just have to flip the board to approach this differently.

_**How to actually do this?**_

I think the solution is quite straightforward.

- Make the characters slower to age so in one hour of gameplay time all the significant characters don't die. And add events specific to them to allow maximum role play where players can recreate the events of the story and how they manage to deal with them.

- Reduce the size of the map, less counties, less duchies and make something more stylized. In the original WC2 and WC3 strategy games the map looked more... normal because it didn't need to accommodate the constraints of an MMORPG leveling zone design. You could use that to inspire you! I know its not perfect but take a look at the two examples below:

Eastern Kingdoms: https://www.deviantart.com/kuusinen/art/Eastern-Kingdoms-Before-the-First-War-Map-I-609428138

Kalimdor: https://preview.redd.it/jlry1igvjg231.png?width=1240&format=png&auto=webp&s=ab00a3267c1c5c0a20b05c149800365ddc99269a

- In a CK3 environment the lore was made for a Tall gameplay style where its not so much the expansion but how you problem solve and thrive with what you have been giving. So instead of having hundreds of characters, flags and factions whats really needed are hundreds of decisions, scripted events, gameplay mechanics for each race and maybe even specific characters where they can roleplay a 50 year time period what would normally be like 300 years in a normal CK3 game. Because this allows you to grow more attached to your characters and their losses to be much, much more significant.

Thank you for your time.

**Comment by helloruhe** [comment]
closed as not possible
